require.config({
	paths:{
	 'echarts' : 'js/echarts/echarts-original',
	'echarts/chart/force' : 'js/echarts/echarts-original',
	'echarts/chart/chord' : 'js/echarts/echarts-original'
	 
	}
	});
	
	require(
	[
	'echarts',
	
	'echarts/chart/force',
	'echarts/chart/chord'
	
	],

	function(ec){
		var myChart = ec.init(document.getElementById('main2')); 
		option = {
     title : {
					text : "微博传播关系图",
					subtext : "数据来自微博",
					x : "right",
					y : "bottom",
					padding : [ 10, 30 ],
					textStyle:{
					color:'#000000'
					}
				},toolbox: {
        show : true,
        feature : {
           
            dataView : {show: true, readOnly: false},
          
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
     tooltip : {
					trigger : "item",
					formatter : "{a0}:{b0}<br>情感值:{d}",
					borderRadius : 3,
					backgroundColor : "rgba(0,0,0,0.4)",
					padding : 4,
					axisPointer : {
						type : 'none',
						lineStyle : {
							color : '#4b8',
							width : 2,
							type : 'dashed'
						},
						crossStyle : {
							color : '#1e90ff',
							width : 5,
							type : 'dashed'
						},
						shadowStyle : {
							size : 'auto',
							color : 'rgba(150,150,150,0.3)'
						}
					}
				},
 color : [ '#ff7f50', '#87cefa', '#da70d6', '#32cd32', '#6495ed', 
    '#ff69b4' ],
    legend: {
        x: 'left',
        data:[{
						name : "中心节点",
						textStyle : {
							color : "#ff7f50"
						}
					},{
						name : "一级节点",
						textStyle : {
							color : "#87cefa"
						}
					}, {
						name : "二级节点",
						textStyle : {
							color : "#da70d6"
						}
					},{
						name : "三级节点",
						textStyle : {
							color : "#32cd32"
						}
					},{
						name : "四级节点",
						textStyle : {
							color : "#6495ed"
						}
					},{
						name : "五级节点",
						textStyle : {
							color : "#ff69b4"
						}
					}]
    },
    series : [
        {
            type:'force',
            name : "转发关系",
            ribbonType: false,
            categories : [
                {
						name : "中心节点",
						"symbolSize": 8
					},
                 {

						name : "一级节点","symbolSize": 4

					},{

						name : "二级节点", "symbolSize": 3

					}
                ,{

						name : "三级节点", "symbolSize": 2.8

					},{

						name : "四级节点", "symbolSize": 2.5

					},{

						name : "五级节点", "symbolSize": 2

					}
            ],
            itemStyle: {
                normal: {
                    label: {
                        show: false,
                        textStyle: {
                            color: '#333'
                        }
                    },
                    nodeStyle : {
                        brushType : 'both',
                        borderColor : 'rgba(255,215,0,0.4)',
                        borderWidth : 1
                    },
                    linkStyle: {
                        type: 'curve'
                    }
                },
                emphasis: {
                    label: {
                        show: false
                        // textStyle: null      // 默认使用全局文本样式，详见TEXTSTYLE
                    },
                    nodeStyle : {
                        //r: 30
                    },
                    linkStyle : {}
                }
            },
            useWorker: false,
            minRadius : 15,
            maxRadius : 25,
            gravity: 1.1,
            scaling: 1.1,
            roam: 'move',
            nodes:[
            {"name":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","value": "Neutral","category":0},
{"name":"<1> 星星的达人: 转发微博 ","value": "Neutral","category":1},
{"name":"<2> 东昌王学增: 有用吗？ ","value": "Negative","category":1},
{"name":"<3> 张文庆_Zwq: 呵呵","value": "Negative","category":2},
{"name":"<4> 小白_挚爱抽抽: 转发微博 ","value": "Neutral","category":1},
{"name":"<5> Spectre_Dai: 转发微博 ","value": "Neutral","category":1},
{"name":"<6> Eyebrow_who: 一点不满意，其实只有联通的降的比较靠谱，其他的什么夜间包节假日包……夜间和节假日我不会回家用wifi啊[微笑][拜拜]","value": "Negative","category":2},
{"name":"<7> 堇色沙滩: 前任总理管不住房价，没想到这任总理连流量都管不了。 ","value": "Negative","category":1},
{"name":"<8> WHY_Magneto: 总理！这就是在忽悠你呢。换汤不换药。 ","value": "Negative","category":1},
{"name":"<9> WOOWOWOO: @嗱_嗱嗱  ","value": "Neutral","category":1},
{"name":"<10> 风吹云走他乡客: ","value": "Neutral","category":2},
{"name":"<11> 真假仙卖包子: 转发微博 ","value": "Neutral","category":1},
{"name":"<12> Crazy_You: 总理至于你满不满意反正广大网友是不满意… ","value": "Negative","category":1},
{"name":"<13> 吃辣条长大的孩纸: 不清零有个毛线用，哪个月不是日子没到就没流量了[顶] ","value": "Negative","category":1},
{"name":"<14> 马好颂: 好 ","value": "Positive","category":1},
{"name":"<15> 酒话斋主: 我好像听到了 pia  pia  pia ","value": "Neutral","category":1},
{"name":"<16> 瞧_布斯: 总理，这三个王八蛋不听话，忽悠您，打他[doge][doge][doge][doge] ","value": "Negative","category":1},
{"name":"<17> Mr金山老妖: 联通坑爹，说了等于没说，全国流量还是贵得要死 ","value": "Negative","category":1},
{"name":"<18> 犟牛Z向前冲: 转发微博 ","value": "Neutral","category":1},
{"name":"<19> 轻酶煮酒ShawnTu_: mark ","value": "Neutral","category":1},
{"name":"<20> 小卒无命: 全是坑，属移动的最大！！！ ","value": "Negative","category":1},
{"name":"<21> 中国通信小小兵: 转发微博 ","value": "Neutral","category":1},
{"name":"<22> 诺基亚WP粉丝团: 转发微博 ","value": "Neutral","category":1},
{"name":"<23> 笑话好贱: 还是很贵[黑线] ","value": "Negative","category":1},
{"name":"<24> Taen_lx: 转发微博 ","value": "Neutral","category":1},
{"name":"<25> ICEICEICE_YH: 转发微博 ","value": "Neutral","category":1},
{"name":"<26> 深圳李文海: 就是忽悠人的[拳头] ","value": "Negative","category":1},
{"name":"<27> 柒夙QISU: 第一条就让我觉得用联通的真是棒棒的……","value": "Positive","category":3},
{"name":"<28> kimi啊啊啊: 为什么三个公司不可以共享号码 换运营公司意味着换手机号码真的很烦诶","value": "Neutral","category":2},
{"name":"<29> Coke_Man: 新一轮眼花缭乱的营销活动而已，记得小时候看报纸每个月药品都会强制降价，可后来呢？","value": "Negative","category":2},
{"name":"<30> 安东尼霍普金斯12: 电信 ","value": "Neutral","category":2},
{"name":"<31> 月光如骨1218: 然而并没有便宜多少 ","value": "Negative","category":2},
{"name":"<32> 人渣哲: 感谢李克强总理，感谢三大运营商[泪][泪][泪][泪] ","value": "Positive","category":2},
{"name":"<33> zhong乐悠悠2013: ","value": "Neutral","category":2},
{"name":"<34> 军军仙深: 转发微博 ","value": "Neutral","category":1},
{"name":"<35> Key-liu: 然而并没有什么卵用","value": "Negative","category":2},
{"name":"<36> 许敏俊xi: @落凝Yim ","value": "Neutral","category":1},
{"name":"<37> 请叫我绅士吧: 傻逼电信没有流量不清零？","value": "Negative","category":3},
{"name":"<38> Cherry小洋: 转发微博 ","value": "Neutral","category":1},
{"name":"<39> 红河丶金刚芭比o: 联通就那点B东西 ","value": "Negative","category":1},
{"name":"<40> 西安靖春: 这个必须赞一个，总理都发话了[微笑] ","value": "Positive","category":1},
{"name":"<41> 深圳齐普生: 转发微博 ","value": "Neutral","category":1},
{"name":"<42> Osi_C: 看完移动，“嗯~”；再往下看，“啊？！” ","value": "Neutral","category":1},
{"name":"<43> ASE一个葫芦:  ","value": "Neutral","category":2},
{"name":"<44> 观众席观众: 去NMB的夜间包定向包半年包，敢在正常流量包上减吗！？ ","value": "Negative","category":1},
{"name":"<45> BilsonLiu: 比较好奇这些措施什么时候开始，让利不大，然后再等两年就更扯淡了 ","value": "Negative","category":1},
{"name":"<46> 极品公子挚爱: 没什么实质性变化 ","value": "Negative","category":1},
{"name":"<47> 第七碗茶: 然而，我却觉得实用性不强。@菱洲藕榭_ @李闩闩  ","value": "Negative","category":1},
{"name":"<48> 抽烟看球的老刘: 领导人发话就是不一样","value": "Positive","category":2},
{"name":"<49> 狼不才: 呵呵","value": "Negative","category":2},
{"name":"<50> Barnett-林: [吃惊]","value": "Neutral","category":2},
{"name":"<51> 漫游冬天: 转发微博 ","value": "Neutral","category":1},
{"name":"<52> 11-HamBurger: 联通这什么屌[打脸]草泥马之前定向流量最便宜的才九块钱啊！腾讯视频也才15块还不限流量！耍猴耍到这地步我建议和移动一起炸妈[打脸]","value": "Negative","category":3},
{"name":"<53> 编号0813: @MissJessie-MissMe 你的流量可以转赠给我了[害羞] ","value": "Positive","category":1},
{"name":"<54> 雷大锤i: 还是联通良心","value": "Positive","category":2},
{"name":"<55> 李凌纪: 看不出哪里降了，简直忽悠强哥","value": "Negative","category":2},
{"name":"<56> 中土世界旅行者: 没见着有什么真正优惠。夜间流量只有给值夜班的用用吧？电信宽带才提至4M，五年前就在用了 ","value": "Negative","category":1},
{"name":"<57> NISHIKI_SASAKI: 额~~~感觉对我没有什么影响的啊，要订的套餐还是一样啊~~~ ","value": "Neutral","category":1},
{"name":"<58> 我是我_: 转发微博 ","value": "Neutral","category":1},
{"name":"<59> 加纳凉子: 完全没看到降价 ","value": "Negative","category":1},
{"name":"<60> 山泉散漫绕街流: [赞] ","value": "Positive","category":1},
{"name":"<61> 大柚子猫: [草泥马]移动的闲时流量原来不是5元1G吗。。为毛还涨价了啊。。","value": "Negative","category":2},
{"name":"<62> 海宁邵峰: 又是套餐！ ","value": "Neutral","category":1},
{"name":"<63> WP8全球新闻: 这TMD地叫降价... ","value": "Negative","category":1},
{"name":"<64> 新浪科技: 你们满意么 ","value": "Neutral","category":1},
{"name":"<65> 龚龑YAN-: 我喜欢联通流量可以转赠这点 ","value": "Positive","category":1},
{"name":"<66> 潘建文Amtor: ","value": "Neutral","category":2},
{"name":"<67> 小黑猫ziye: ","value": "Neutral","category":2},
{"name":"<68> 龚玖伦Hunter: 联通的感觉还行，移动一如既往的坑","value": "Neutral","category":2},
{"name":"<69> 杰王子_XJ: 糊弄人的","value": "Negative","category":2},
{"name":"<70> Kev_刘羽: Mark一下，准备退款 ","value": "Neutral","category":1},
{"name":"<71> 馳胖儿: 糊弄鬼呢！！！这么213的政策。。。 ","value": "Negative","category":2},
{"name":"<72> luckyboy_20665: 转发微博 ","value": "Neutral","category":1},
{"name":"<73> 肖丽君-lj: 转发微薄[爱你哦] ","value": "Neutral","category":1},
{"name":"<74> OTT-汪: 优惠个妹！ ","value": "Negative","category":1},
{"name":"<75> 布绒琦乐屋: 转发微博 ","value": "Neutral","category":1},
{"name":"<76> 丿晴天小猪丶: 大部分政策之前都有，甚至比这更优惠，只是大家都不知道罢了。 ","value": "Positive","category":1},
{"name":"<77> Emulex: [放大镜][放大镜][放大镜] ","value": "Neutral","category":1},
{"name":"<78> 朱津宏Heath: 转发微博 ","value": "Neutral","category":1},
{"name":"<79> Shaw_m: 总理说话不顶事儿，总经理说了才有用","value": "Positive","category":2},
{"name":"<80> 未完待续_tbc: 总经理骗总理。[挖鼻] ","value": "Negative","category":1},
{"name":"<81> Gonzalito瓜瓜: 大部分都是擦边球，没啥实质变化，移动那个最坑 ","value": "Negative","category":1},
{"name":"<82> 杨泽东015: @埃及艳后- 知道你4G的疾苦","value": "Neutral","category":2},
{"name":"<83> 大连理财时间: 推荐[嘻嘻] ","value": "Positive","category":1},
{"name":"<84> King_Liang2013: 没用 ","value": "Negative","category":2},
{"name":"<85> 君抹: 换汤不换药 不过宽带提速 到还是有一点 ","value": "Negative","category":1},
{"name":"<86> Disaur: 其实比美国部分运营商的流量费要便宜了吧 ","value": "Positive","category":1},
{"name":"<87> LRP不是牛奶瓶: 然而并没有什么卵用。 ","value": "Negative","category":1},
{"name":"<88> Lumia-Song-Mac: 都没诚意 ","value": "Negative","category":1},
{"name":"<89> Edwin今晚打老虎: 降个毛线，全特么在扯蛋！ ","value": "Negative","category":1},
{"name":"<90> heavens-yang: ","value": "Neutral","category":2},
{"name":"<91> 悠悠谷: 完全木有看出有降价，移动的夜间流量套餐还涨了1倍！ ","value": "Negative","category":1},
{"name":"<92> SUN11308: 转发微博 ","value": "Neutral","category":1},
{"name":"<93> faylin_blue: 能说简单点吗？我其实就是想知道我现在用的套餐是要降价呢，还是要增加流量，套餐内的流量也不清零吗？还是套餐都不变，就是动动我不怎么用的流量包意思一下？ ","value": "Neutral","category":1},
{"name":"<94> 江持的奇局rofL: 然而并没有什么卵用","value": "Negative","category":2},
{"name":"<95> 兰亭序xia:  ","value": "Neutral","category":2},
{"name":"<96> 地球是什么球: 转发微博 ","value": "Neutral","category":1},
{"name":"<97> 星空漫语19910426: @李克强 ","value": "Neutral","category":1},
{"name":"<98> 周锅圈: 联通电信良心。移动还是在打小算盘。[拜拜] ","value": "Positive","category":1},
{"name":"<99> 欧欧琳琅: 还是联通实在啊 ","value": "Positive","category":2},
{"name":"<100> 曲占东: 没诚意，忽悠总理，该当何罪？[怒骂] ","value": "Negative","category":1},
{"name":"<101> 任怨RY: 然而，有个卵用？？？ ","value": "Negative","category":1},
{"name":"<102> 古波波的: ","value": "Neutral","category":2},
{"name":"<103> 温雪微蜜2929106795: 转发微博 ","value": "Neutral","category":1},
{"name":"<104> jessicagreat: 没有实质性变化 ","value": "Negative","category":1},
{"name":"<105> billinsh: 转发微博 ","value": "Neutral","category":1},
{"name":"<106> 油油D: 转发微博 ","value": "Neutral","category":1},
{"name":"<107> 大黄守着你:  @无敌小野猴 还能更不要脸一点么 ","value": "Negative","category":1},
{"name":"<108> 蒋科平: 总结的真好，看完发现有的不但没降还涨了。我啥也不要，你移动能在我现在这个套餐资费不变的基础上让我的5能用上4G就好。 ","value": "Negative","category":1},
{"name":"<109> 市井晓人: 躲躲闪闪 就是不好好说话  ","value": "Negative","category":1},
{"name":"<110> Kevin--Lau: [哈哈][哈哈][哈哈]赞同","value": "Positive","category":2},
{"name":"<111> CHen福森: 忽悠","value": "Negative","category":2},
{"name":"<112> xak简单: 转发微博 ","value": "Neutral","category":1},
{"name":"<113> vermouth_APTX: 从10元70m到10元1g，可见你们之前的资费多坑爹了！ ","value": "Negative","category":2},
{"name":"<114> 北秋走马: 看完移动的就不想往下看了！！ ","value": "Neutral","category":1},
{"name":"<115> 命运之匙: 转发微博 ","value": "Neutral","category":1},
{"name":"<116> change变变: 转发微博 ","value": "Neutral","category":1},
{"name":"<117> 许文广: 转发微博 ","value": "Neutral","category":1},
{"name":"<118> fuyunc: 转发微博 ","value": "Neutral","category":1},
{"name":"<119> 精卫埴海: 说得专业","value": "Neutral","category":2},
{"name":"<120> 古月中心相心: 然而并没有什么卵用 ","value": "Negative","category":2},
{"name":"<121> 汐山芙伖Ukami: [微笑]","value": "Neutral","category":2},
{"name":"<122> 沙包残念: 电信这个感觉还不错。。就是不知道四川电信会搞成啥样","value": "Positive","category":2},
{"name":"<123> reicn: 移动你妹喊你回家吃饭。 ","value": "Neutral","category":1},
{"name":"<124> 专门调戏舰娘的萌豚提督: ","value": "Neutral","category":2},
{"name":"<125> Abuser: 赤裸裸的打脸。 ","value": "Negative","category":1},
{"name":"<126> 奔波的鱼: 竟是虚的 ","value": "Negative","category":2},
{"name":"<127> honey当你: 转发微博 ","value": "Neutral","category":1},
{"name":"<128> 豆腐羹V: 转发微博 ","value": "Neutral","category":1},
{"name":"<129> liy-x: ","value": "Neutral","category":2},
{"name":"<130> 低调的Liz: 不在乎说了多少话，而是在于谁说的[嘻嘻] ","value": "Neutral","category":1},
{"name":"<131> WIV哥哥: 不滿意 ","value": "Negative","category":2},
{"name":"<132> 前事莫言旧梦莫提: 呵呵 ","value": "Neutral","category":1},
{"name":"<133> PapaverSomnus:  ","value": "Neutral","category":2},
{"name":"<134> Monster零号: 移动夜间1G还不能使用4G网。。。。。 ","value": "Neutral","category":1},
{"name":"<135> pyb大大: 转发微博 ","value": "Neutral","category":1},
{"name":"<136> GarethLE: 转发微博 ","value": "Neutral","category":1},
{"name":"<137> 周鼎舵: [doge][喵喵]","value": "Neutral","category":2},
{"name":"<138> CC二郎: 不咋的 ","value": "Negative","category":1},
{"name":"<139> 戴三个表Tadpole:  ","value": "Neutral","category":2},
{"name":"<140> 风沐浴张赛: ","value": "Neutral","category":2},
{"name":"<141> 求不贰2: 降在哪 ","value": "Negative","category":1},
{"name":"<142> 乌衣弄小少: 我真特么日了[狗]了！这特么是降价？！！[doge][doge][doge] ","value": "Negative","category":1},
{"name":"<143> 风飘颺: 转发微博 ","value": "Neutral","category":1},
{"name":"<144> 甄总萌萌哒: 这不光是质疑人民智商，还是质疑总理的智商，赞！ ","value": "Negative","category":2},
{"name":"<145> 没头脑姚: 转联通 ","value": "Neutral","category":2},
{"name":"<146> 寒假不想看书君: 放NM的血啊，移动夜间流量10元1g，现在不是5元1g吗？rlgl！","value": "Negative","category":2},
{"name":"<147> 前峰w伟: 在网三年能买10块=1.5G 我居然够。。。@硬朗才俊 [喵喵] ","value": "Neutral","category":1},
{"name":"<148> 我晕我又帅了vlv: 然而并没什么卵用…联通10元1.5G你得在网三年才能办[doge] ","value": "Negative","category":1},
{"name":"<149> 平-易: 毫无诚意 ","value": "Negative","category":1},
{"name":"<150> ACSun_zlz: 这也叫图，你是在逗我吗","value": "Negative","category":2},
{"name":"<151> sukiko789: 电信宽带，移动流量不清零","value": "Neutral","category":3},
{"name":"<152> 坤少3599: 联通最没诚意，拿电信日的活动糊弄","value": "Negative","category":2},
{"name":"<153> 坛旺: 好热闹，而已。","value": "Neutral","category":2},
{"name":"<154> Alfred喜怒无常: 转需 ","value": "Neutral","category":2},
{"name":"<155> sh-sf: 到底哪优惠。。。了","value": "Negative","category":2},
{"name":"<156> 锁向披靡: 跟我没任何关系，没一项复合优惠条件的。","value": "Negative","category":2},
{"name":"<157> 牵手奔跑89080: 也是个坑 ","value": "Negative","category":1},
{"name":"<158> Brandonwang13: 有个屁用 ","value": "Negative","category":2},
{"name":"<159> 金臣龙YoonA: 转发微博 ","value": "Neutral","category":1},
{"name":"<160> 利托里奥厨: 不满意，建议智障移动赶快申请倒闭","value": "Negative","category":3},
{"name":"<161> 花前肉下: 全是看上去很美系列， ","value": "Neutral","category":2},
{"name":"<162> Ocean_Qi: 大three可是一毛钱一兆 ","value": "Neutral","category":2},
{"name":"<163> SHENPAI的微博: 降个屁，照样贵[doge] ","value": "Negative","category":1},
{"name":"<164> 胖子的世界o_O: ","value": "Neutral","category":2},
{"name":"<165> 雾中人Mr-D: ","value": "Neutral","category":2},
{"name":"<166> 小曾伯伯: 不痛不痒，你们大爷的@中国电信 @中国移动 @中国联通 [怒][怒][怒] ","value": "Negative","category":1},
{"name":"<167> 奥利奥包子: 转发微博 ","value": "Neutral","category":1},
{"name":"<168> 马鲛鱼_Huck: 我现在还是2G套餐","value": "Neutral","category":2},
{"name":"<169> 寻光阁主人: ","value": "Neutral","category":2},
{"name":"<170> boy最佳听众: 转发微博 ","value": "Neutral","category":1},
{"name":"<171> TonyNg: 不要脸。 ","value": "Negative","category":1},
{"name":"<172> X教授不在家: 毫无诚意 ","value": "Negative","category":2},
{"name":"<173> 黑色好心情: 转发微博 ","value": "Neutral","category":1},
{"name":"<174> xvx墨鱼: 并没有什么卵用 ","value": "Negative","category":1},
{"name":"<175> 美国队长十三叔: 移动去死吧。","value": "Negative","category":2},
{"name":"<176> 疯猴砸王琳: 怎么感觉还是那么的贵啊   没有什么区别 ","value": "Negative","category":1},
{"name":"<177> 漫游环球: ","value": "Neutral","category":2},
{"name":"<178> 史上最拽的大侠: 然而移动又来坑爹，夜间流量起个球用!! ","value": "Negative","category":1},
{"name":"<179> AgentTSY: 好事啊！ ","value": "Positive","category":1},
{"name":"<180> 佛佑良善: @航海的萌琦: 还是贵的要死 ","value": "Negative","category":1},
{"name":"<181> Mr聰小白: 上有政策下有对策的经典教科书式的典范，实在佩服 ","value": "Positive","category":2},
{"name":"<182> 左目大叔: 满意个毛！夜间优惠有个什么卵用！套餐资费哪有下降，明明变相推广套餐！宽带提速不就是把原来限制的带宽放开了而已，难道还要感谢他们吗？ ","value": "Negative","category":2},
{"name":"<183> 一枝不倒的枪: 无任何吸引力 ","value": "Negative","category":1},
{"name":"<184> LGD_Roden: 转发微博 ","value": "Neutral","category":1},
{"name":"<185> Derrick-Rose-1: 换汤不换药 ","value": "Negative","category":1},
{"name":"<186> 即将爆炸: 降尼玛个鸡巴","value": "Negative","category":2},
{"name":"<187> 理查德查德: 这是侮辱总理的智商么 ","value": "Negative","category":2},
{"name":"<188> 周帛W: 看着好像是来捞钱的 ","value": "Negative","category":2},
{"name":"<189> 公子和小宝: 转发微博 ","value": "Neutral","category":1},
{"name":"<190> a-sing-: 好像看不出什么很吸引人的，[睡][睡][睡] ","value": "Negative","category":1},
{"name":"<191> 伟1006: 全TM是一堆鸡肋 ","value": "Negative","category":2},
{"name":"<192> Z-St13: 转发微博 ","value": "Neutral","category":1},
{"name":"<193> Yoooo伪高冷: 移动对于我这个小市民来说 还是没什么特别的优势[拜拜]","value": "Negative","category":2},
{"name":"<194> 大猫和小猫1: 转发微博 ","value": "Neutral","category":1},
{"name":"<195> MichaelDanZ: 我能说不怎么地嘛[抠鼻屎] ","value": "Negative","category":1},
{"name":"<196> 小蕾子哈哈-: 然而并没有什么卵用[拜拜] 移动不听话[打脸] 强哥削他[doge] ","value": "Negative","category":1},
{"name":"<197> 老K出品: 看中国移动又来忽悠总理和老百姓了。 ","value": "Negative","category":1},
{"name":"<198> magicKOU: 这都是些什么鬼！？开夜间流量顶个毛用！","value": "Negative","category":2},
{"name":"<199> 15c爱木: ","value": "Neutral","category":2},
{"name":"<200> Mast2r易昊: 口可口可 ","value": "Neutral","category":1},
{"name":"<201> 吃葡萄说葡萄不吃不舒服司机:  ","value": "Neutral","category":2},
{"name":"<202> 不愿透露姓名的王心怿: 然而并没有什么卵用 ","value": "Negative","category":3},
{"name":"<203> 梦月天冰: ","value": "Neutral","category":2},
{"name":"<204> 药师寺节园: 没感到下滑，对比移动太坑 ","value": "Negative","category":1},
{"name":"<205> 温斯洛克: 这都是以前的方案，都用烂了","value": "Negative","category":2},
{"name":"<206> 挪威的森林0501: 三大运营商确实有推出了惠民政策，最明显的就是宽带的大幅提速。但也藏了不少小算盘甚至是“坑爹”的优惠：便宜的流量包时间设置在了半夜，好多措施都是换个名称的旧服务。当然还有各家此次借机大力推广4G业务。#运营商太机智# 白天的流量能优惠点不[疑问] ","value": "Positive","category":1},
{"name":"<207> 盐A桃: 转发微博 ","value": "Neutral","category":1},
{"name":"<208> 祈祷者praying: 回复@初之心时尚:总经理不能忽悠，忽悠下总理还是可以的～至于流量不清零，三大运营商都不鸟老李～ ","value": "Negative","category":1},
{"name":"<209> 轻舞剑尘: 最讨厌人家一脸善意的问，请问您是吃大便还是吃屎呢？或者我们帮您准备了包翔套餐。妈的恶心到吐，我能不吃这些东西吗。","value": "Negative","category":2},
{"name":"<210> 石黑曜:  ","value": "Neutral","category":2},
{"name":"<211> 吃鹿的草: ","value": "Neutral","category":2},
{"name":"<212> 尊贵黄铜: 并不满意","value": "Negative","category":2},
{"name":"<213> 钟先生的喜事: 确实不懂，以我短浅目光和捉急智商。 ","value": "Negative","category":1},
{"name":"<214> __王梓华: cx。","value": "Neutral","category":2},
{"name":"<215> 李何冉: ","value": "Neutral","category":2},
{"name":"<216> 后来不见不散: [doge] ","value": "Neutral","category":1},
{"name":"<217> 诺坎普666: 然而并没有什么卵用","value": "Negative","category":2},
{"name":"<218> 139王志涛: 工信部的官员们看看这@央视新闻 @王思聪 @工信微报 @新浪科技  ","value": "Neutral","category":1},
{"name":"<219> 身残志坚也无糖: ","value": "Neutral","category":2},
{"name":"<220> 岳阳联通宽带受理XR: 转发微博 ","value": "Neutral","category":1},
{"name":"<221> SimGenius: 联通能优先走本地流量吗→_→ ","value": "Neutral","category":2},
{"name":"<222> Jerry的拉普拉斯变换: 丝毫没感觉到便宜[黑线][黑线]玩数字游戏，别骗我，我上过小学[失望][失望]#三大运营商提速降费# 没有政策的时候，@中国联通 搞活动1元1G流量，国家政策来了，美名其曰降费活动价10元1g[眼泪][眼泪]","value": "Negative","category":2},
{"name":"<223> yeleiyu: 然而并没什么卵用。。。。 ","value": "Negative","category":1},
{"name":"<224> 阿邪: 这个力度还是继续忽悠总理吧 ","value": "Negative","category":1},
{"name":"<225> AFannyGirl: 转发微博 ","value": "Neutral","category":1},
{"name":"<226> 前任泡的茶: 转发微博 ","value": "Neutral","category":1},
{"name":"<227> 禹stone: 不满意","value": "Negative","category":2},
{"name":"<228> 红颜还是蓝颜知己: 转发微博 ","value": "Neutral","category":1},
{"name":"<229> 广西工业职业技术学院贴吧: ","value": "Neutral","category":2},
{"name":"<230> 鬼束Komorebi: 转发微博 ","value": "Neutral","category":1},
{"name":"<231> 林松峰: 说的好[赞]","value": "Positive","category":3},
{"name":"<232> 余太的余先生: ","value": "Neutral","category":2},
{"name":"<233> ChingYu_Sung: 转发微博 ","value": "Neutral","category":1},
{"name":"<234> 偏执LeoH: 。。 ","value": "Neutral","category":1},
{"name":"<235> 白--蓝: 提速后谁家能通过有公信力的网络测速，降费后谁家最便宜实惠，那就用谁家的。用户得到了哪家的优惠，自然会用脚投票，选择的就是满意的。 ","value": "Positive","category":2},
{"name":"<236> 丶MaiDang: 当全国人民是逗比 ","value": "Negative","category":2},
{"name":"<237> 前宸似锦: 转发微博 ","value": "Neutral","category":1},
{"name":"<238> 晨明希: 糊弄傻逼呢，真不把总理当个事！夜间流量给谁用！来来来那几个老总你出来，我保证不打死你 ","value": "Negative","category":2},
{"name":"<239> 改昵称什么的最头痛了: 也是艺术啊 ","value": "Neutral","category":2},
{"name":"<240> 朕元大仙: 泥煤，泥煤！！刚花了100大洋买了1.5G ","value": "Negative","category":1},
{"name":"<241> 飘渺-珂珂: 弱爆了，就是普通的电信日营销而已 ","value": "Negative","category":1},
{"name":"<242> 石头Life: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz ","value": "Neutral","category":1},
{"name":"<243> 完颜许哲Jason-USTC: 其实没啥吸引力… ","value": "Neutral","category":1},
{"name":"<244> 我有一颗红蓝心: 都是文字游戏就不能同意一下，1G流量就是多少钱，和哪个时间段都没有关系","value": "Neutral","category":2},
{"name":"<245> DJjiang_: 10元包1.5G省内流量@小镇土鳖青年 @Yowsen 1G全国流量包呢？ ","value": "Neutral","category":1},
{"name":"<246> 黄曼塞: 领导们都白天睡觉，半夜上班咯？ ","value": "Neutral","category":1},
{"name":"<247> 桔子酱Jamjamjam: 完全不满意 ","value": "Negative","category":2},
{"name":"<248> 玩坤: 上有政策，下有对策。坑是换汤不换药。 ","value": "Negative","category":1},
{"name":"<249> 红黑正正: 说了半天全是废话，等于没降 ","value": "Negative","category":1},
{"name":"<250> 贝贝贝_贝: 我就对流量不清零有兴趣[doge] 习大大真","value": "Negative","category":1},
{"name":"<251> 耳列偷: 转发微薄[放假啦] ","value": "Neutral","category":1},
{"name":"<252> 沈大霸: 联通良心啊 ","value": "Positive","category":2},
{"name":"<253> iPony-Ma: 总理，您怎么看…","value": "Neutral","category":2},
{"name":"<254> MADshionn: 电信把用户体验搞搞上去就蛮好了、伐要每天10000打过来搞七捏三 ","value": "Neutral","category":1},
{"name":"<255> 小科332: 呵呵 ","value": "Neutral","category":2},
{"name":"<256> 可乐素巧克力控: ","value": "Neutral","category":2},
{"name":"<257> 日斜影迟归: 我要回家，网速慢的甚少超过100KB还每个月25欧…","value": "Negative","category":2},
{"name":"<258> 烤火鸡腿: 我就笑笑，不说话 ","value": "Neutral","category":1},
{"name":"<259> 柏吃支醉: 然而这并没有什么卵用","value": "Negative","category":2},
{"name":"<260> 明明就丶她比较温柔: 该赚的还是赚。 很多活动以前就有了。 听着好听实际上没有优惠多少 ","value": "Neutral","category":2},
{"name":"<261> uncle____wang:  ","value": "Neutral","category":2},
{"name":"<262> 蛮满说要减肥好嘛: 夜间有什么用。。Wi-Fi在的好吗 联通好点 ","value": "Neutral","category":2},
{"name":"<263> Cen儿里来的: 在侮辱总理和我们大众的智商吗？ ","value": "Negative","category":1},
{"name":"<264> Sunny上上签: 转发微博 ","value": "Neutral","category":1},
{"name":"<265> Han志军: 转发微博 ","value": "Neutral","category":1},
{"name":"<266> Vincent_SK_Fan: 轉發微博 ","value": "Neutral","category":1},
{"name":"<267> YH铎: 转发微博 ","value": "Neutral","category":1},
{"name":"<268> 宠物医生乐乐: ","value": "Neutral","category":2},
{"name":"<269> 羊不少: 上面喊话，下面糊弄！都允许竞争不就没这破事了么，没劲！再说了一边要市场化运营，一边还要听政府话，矛盾，扭曲。","value": "Negative","category":2},
{"name":"<270> 大大Stefan: 说好的10块钱1G流量呢 ","value": "Neutral","category":1},
{"name":"<271> 郭小雅爸爸的葡萄藤: 转发微博 ","value": "Neutral","category":1},
{"name":"<272> 二毛我不饿: 有卵用？ ","value": "Negative","category":2},
{"name":"<273> neversaydie357: 中移动最王八 ","value": "Neutral","category":1},
{"name":"<274> 传说世界真的可以: 转发微博 ","value": "Neutral","category":1},
{"name":"<275> SMFWebo: 要不是李发话了这些铁公鸡的套餐指不定还要用几年 ","value": "Negative","category":1},
{"name":"<276> 徐笑笑Adam: 没劲 ","value": "Negative","category":1},
{"name":"<277> 秦-恒: [喵喵] ","value": "Neutral","category":1},
{"name":"<278> 是个MADAO: 这算欺君之罪吧[怒] ","value": "Negative","category":1},
{"name":"<279> 叮噹小麗: ","value": "Neutral","category":2},
{"name":"<280> 帷幕: 对就特么的忽悠","value": "Negative","category":2},
{"name":"<281> 少林收垃圾研究僧: 我10块钱3g的夜间流量。。。。 ","value": "Neutral","category":1},
{"name":"<282> TEITA: 转发微博 ","value": "Neutral","category":1},
{"name":"<283> 林松峰: 还是坑~换了一种挖坑的方式！ ","value": "Negative","category":1},
{"name":"<284> LLkey: 对总理的话 打下擦变球而已[挖鼻]套餐内的流量不还是那样吗","value": "Negative","category":2},
{"name":"<285> 梁额头blingbling: @叉傅傅 [doge] ","value": "Neutral","category":3},
{"name":"<286> 低调的山: 转发微博 ","value": "Neutral","category":1},
{"name":"<287> 乐柚_: 并不满意 ","value": "Negative","category":2},
{"name":"<288> 静水长老: 夜间流量大优惠？！谁晚上回家没有WiFi？习大大都不赞成熬夜，运营商你想干嘛？[弱] ","value": "Negative","category":1},
{"name":"<289> bzfdu: 基本上都没降，移动那个夜间1G现在就是5元，调整后居然变10元了[doge]电信那个4G套餐也很坑爹，价格跟移动现在的一样，但是移动送的是1G通用流量[拜拜]只有联通那个10块钱的包还行，不过也是要网龄限制的吧。 ","value": "Negative","category":1},
{"name":"<290> 痞人北极熊16: 转发微博 ","value": "Neutral","category":1},
{"name":"<291> junwei: 转发微博 ","value": "Neutral","category":1},
{"name":"<292> 亦木lk: ","value": "Neutral","category":2},
{"name":"<293> 秦邮俗人: 我是联通，10元1.5G省内流量包早就有了，现在还出来说，一点诚意都没有！这次的降价，我真替你们运营商心疼，利润好不容易从500%降到499%，真心不容易[笑cry] ","value": "Neutral","category":1},
{"name":"<294> 青青蝶恋Pop: 转发微薄[织] ","value": "Neutral","category":1},
{"name":"<295> 海宁邵峰: 又是套餐！ ","value": "Neutral","category":1},
{"name":"<296> SH司翰: 转需 ","value": "Neutral","category":1},
{"name":"<297> 随意昏沉: 没觉得降了多少","value": "Negative","category":2},
{"name":"<298> 太微子: 上有政策，下有对策。这群人永远不吃亏啊 ","value": "Negative","category":1},
{"name":"<299> 富牛同桌: 转发微博 ","value": "Neutral","category":1},
{"name":"<300> 奔腾的大卫: 专线神马时候能大提速哇 ","value": "Neutral","category":1},
{"name":"<301> 夢想家孟利峰:  ","value": "Neutral","category":2},
{"name":"<302> 郭小莱-Xiaolai: 听说都很忽悠人，坑爹声一大片。 ","value": "Negative","category":1},
{"name":"<303> 因为我叫甘大良: ","value": "Neutral","category":2},
{"name":"<304> 笔下维城: 换汤不换药，坑谁呢 ","value": "Negative","category":1},
{"name":"<305> seele41: @天山云之家 ","value": "Neutral","category":1},
{"name":"<306> 宫本笑外: 打擦边球，先说一下移动，其他真的没什么用就50元2G稍微便宜了一点，不也不知道这个更多城市不清零什么意思，联通嘛坑，1.5G包半年，我半年就用1.5G？包半年的废话不清零，不是包半年的呢，擦边球，电信也是坑谁天天玩夜间流量。三大运营商表面降价，其实没什么降价，国内的运营商应该到10元1G时代 ","value": "Negative","category":1},
{"name":"<307> 一木易青争: 转发微博 ","value": "Neutral","category":1},
{"name":"<308> 红玫贝壳: 50元2G，有没有25元1G的？？ ","value": "Neutral","category":1},
{"name":"<309> 张非仔: 有啥用，看着没优惠到哪去 ","value": "Negative","category":1},
{"name":"<310> YX-NUDTer:  ","value": "Neutral","category":2},
{"name":"<311> 东蹦蹦西跳跳: 就是忽悠人的，什么也没降！ ","value": "Negative","category":1},
{"name":"<312> 战争即和平xx即奴役无知即力量: 中国联通最操蛋 ","value": "Negative","category":1},
{"name":"<313> 陈诗文啊: 然而并没有什么卵用[微笑] ","value": "Negative","category":1},
{"name":"<314> 铁汉柔情喜感妹: 移动那个套餐老子特么都用了半年了你优惠在哪儿啊我次奥！ ","value": "Negative","category":1},
{"name":"<315> 啊權權權兒: 然而并没有什么卵用 ","value": "Negative","category":2},
{"name":"<316> 黄立宏Hlh: +1 ","value": "Neutral","category":1},
{"name":"<317> 康康YES:  ","value": "Neutral","category":2},
{"name":"<318> 三叔与露西: ","value": "Neutral","category":2},
{"name":"<319> MorbidZoophilia_Cer: 并没什么卵用 ","value": "Negative","category":1},
{"name":"<320> P-H-B: 总理一句话为多少百姓争取了利益..周总理后中国又一位好总理 ！顶起！","value": "Positive","category":2},
{"name":"<321> 风中追风的林佳欣: 总理说：看来我的话不好使啊，是时候请王书记出马了[鄙视][鄙视] ","value": "Negative","category":1},
{"name":"<322> Daniel_Dai_: ","value": "Neutral","category":2},
{"name":"<323> 星马豪_: @星宇Iron  ","value": "Neutral","category":1},
{"name":"<324> 蕊落余馨: 转发微博 ","value": "Neutral","category":1},
{"name":"<325> 王骏176: 转发微博 ","value": "Neutral","category":1},
{"name":"<326> 五味瓶: 移动的最坑！ ","value": "Neutral","category":1},
{"name":"<327> zw_stone: 并没有什么卵用 ","value": "Negative","category":2},
{"name":"<328> 圣迷小子: ","value": "Neutral","category":2},
{"name":"<329> 安妮5jhi18qol3: ","value": "Neutral","category":2},
{"name":"<330> 加州风采: →_→ ","value": "Neutral","category":1},
{"name":"<331> 风雨彩虹1970:  ","value": "Neutral","category":2},
{"name":"<332> 荐月: 转发微博 ","value": "Neutral","category":1},
{"name":"<333> slim大祥: 三个这么合起伙来糊弄强哥 合适吗 ","value": "Negative","category":1},
{"name":"<334> 欧阳Page_one: 没看出有什么优惠的。。。 ","value": "Negative","category":1},
{"name":"<335> 你有种再说一遍: 假如总理再说一遍又一遍，他们可能又会推出一万块一万g流量！然而对于老百姓并没有什么卵用[紧张]","value": "Positive","category":3},
{"name":"<336> 行者秋莲: 总理说话也不很管用啊，还是利益好使 ","value": "Negative","category":1},
{"name":"<337> 龙岩学院电脑服务社: 还是太贵啊 ","value": "Negative","category":1},
{"name":"<338> 计量的小竹子: 没没看出来。。降在哪里[doge]","value": "Negative","category":2},
{"name":"<339> Seika-5: 强哥你看看这三大粪箕是如何忽悠你的？ ","value": "Negative","category":1},
{"name":"<340> 石头小昊: ","value": "Neutral","category":2},
{"name":"<341> 毛驴快快快跑: 总理的话果然掷地有声[good] ","value": "Negative","category":1},
{"name":"<342> 不死伪骑: 欺骗自己，欺骗人民，欺骗总理！！！@中国移动 @中国联通 @中国电信 ","value": "Negative","category":1},
{"name":"<343> 酱爆小咸鱼: 还是无比的坑，用户主要是用流量套餐的，而移动修改的资费是晚间闲时和假日的，晚间闲时有多少用户会开？ ","value": "Negative","category":1},
{"name":"<344> 梦月天冰: ","value": "Neutral","category":2},
{"name":"<345> 不吃泡面WT: Repost ","value": "Neutral","category":1},
{"name":"<346> 追风筝的----孩子: ","value": "Neutral","category":2},
{"name":"<347> sui豫er安: 又证明了一个真理 ","value": "Neutral","category":1},
{"name":"<348> 刘淦新: 垄断，狂打强哥脸！ ","value": "Negative","category":1},
{"name":"<349> 杜蚊虫: 呵呵 你觉得呢","value": "Neutral","category":2},
{"name":"<350> 翔蕉Man: [思考][思考][思考] ","value": "Neutral","category":1},
{"name":"<351> 髮型影響網速: 中国联通啊，爱你不容易啊 ","value": "Positive","category":1},
{"name":"<352> 阿狸August: ","value": "Neutral","category":2},
{"name":"<353> 额尔得木图:  ","value": "Neutral","category":2},
{"name":"<354> 转角看见另一个自己: ","value": "Neutral","category":2},
{"name":"<355> 海宝Diana: 要不是嫌换号麻烦，早换联通了，移动的闲时流量对我没用","value": "Negative","category":2},
{"name":"<356> slaywhospeak: ","value": "Neutral","category":2},
{"name":"<357> 用户z5s: ","value": "Neutral","category":2},
{"name":"<358> 落伍者9406: ","value": "Neutral","category":2},
{"name":"<359> 千古传宋: 不满意，电信和移动没诚意。","value": "Negative","category":2},
{"name":"<360> 调哪星: 居然敢耍总理，简直係嫌命长[挖鼻][挖鼻]","value": "Negative","category":2},
{"name":"<361> 用户5524623994: ","value": "Neutral","category":2},
{"name":"<362> 飞翔的石头1307: ","value": "Neutral","category":2},
{"name":"<363> 战马孤影: [弱]不求放开市场，能携号转网也得让三大运营商当孙子 ","value": "Negative","category":1},
{"name":"<364> 广良W: ","value": "Neutral","category":2},
{"name":"<365> 看風聼雨: @中国移动10086 移动毫无诚意，对我毫无影响！差评！ ","value": "Negative","category":1},
{"name":"<366> 云海飘星: ","value": "Neutral","category":2},
{"name":"<367> 小屹爱吃肉: tmobile 40 美金全部无限 [喵喵] ","value": "Neutral","category":2},
{"name":"<368> 柏飞先生: 诚意不足，总理比敢忽悠…… ","value": "Negative","category":1},
{"name":"<369> 管跃辉023: 除了流量不清零、可交易、可转赠，其余就是把现有的各种优惠梳理了一下，换个外套而已，完全没有诚意！该岐山书记出马了！ ","value": "Negative","category":1},
{"name":"<370> 白百列: [委屈]","value": "Neutral","category":2},
{"name":"<371> cm968: ","value": "Neutral","category":2},
{"name":"<372> 1zhu30: 哼哼哼","value": "Neutral","category":2},
{"name":"<373> Mike主页: 忽悠总理 ","value": "Negative","category":1},
{"name":"<374> 沉梦未苏:  ","value": "Neutral","category":2},
{"name":"<375> 加油法拉利: 文盲脑残们你们换4G手机了吗？？手机都不支持4G有什么资格用4G？？ ","value": "Negative","category":2},
{"name":"<376> 刘-智-龙: 响应总理的号召～ ","value": "Positive","category":1},
{"name":"<377> 只是那个人-: 不","value": "Negative","category":2},
{"name":"<378> 玉淇淋: 转发微博 ","value": "Neutral","category":1},
{"name":"<379> 80後縂裁: 糊弄傻子呢 ","value": "Negative","category":2},
{"name":"<380> 萝卜的萝_噢耶: 满意个屁！","value": "Negative","category":2},
{"name":"<381> 曲躍G风何: [睡]上有政策，下有对策，垄断的嘴脸","value": "Negative","category":2},
{"name":"<382> 再这么多僵尸广告粉我就怒弃微博: 有差么[闭眼]还是一样跪[闭眼]","value": "Negative","category":2},
{"name":"<383> Jorai: [右哼哼][左哼哼][怒骂] ","value": "Negative","category":1},
{"name":"<384> WindowsPhone玄隐: 转发微博 ","value": "Neutral","category":1},
{"name":"<385> 我可怜我总是等待: 联通你这是套餐内不变，多用的降价。好机智呀！有多少人会另外开通流量包。fuck 还天天打电话问，烦不烦，不要钱啊！@中国联通 ","value": "Neutral","category":2},
{"name":"<386> 自信未必成功: 转发微博 ","value": "Neutral","category":1},
{"name":"<387> 绅士流亡: 好像对广大手机网民来说，没什么明显的实惠吧，总理您接着催吧，这三大傻不懂您懂的意思！！！！！[doge][弱]","value": "Negative","category":2},
{"name":"<388> yuanlinlynn: ","value": "Neutral","category":2},
{"name":"<389> 零界点之沸: 你们这么忽悠总理，还真不怕总理向你们开刀咩？","value": "Negative","category":2},
{"name":"<390> 我书读得少你不要骗我哦: 没有实质性的惠民，三大运营商脑子被驴踢了么？ ","value": "Negative","category":2},
{"name":"<391> icu北极星: @财经杂志 ","value": "Neutral","category":2},
{"name":"<392> J-concept童生: 中国电信 你的首选 ","value": "Neutral","category":1},
{"name":"<393> I_Monster: 中国移动完全是糊弄人啊哈哈哈哈联通和电信才实在 ","value": "Negative","category":1},
{"name":"<394> 月西星沉: 转发微博 ","value": "Neutral","category":1},
{"name":"<395> 追赶火车的男孩: 这仨小子不听话啊！是有多久没挨打了？ ","value": "Neutral","category":1},
{"name":"<396> 没吃药之前感觉自己萌萌哒: 坑","value": "Negative","category":2},
{"name":"<397> litenly: 尼玛，三坑连总理也敢坑！ ","value": "Negative","category":1},
{"name":"<398> 历途科技: 转发微博 ","value": "Neutral","category":1},
{"name":"<399> 全武装幼女控: 呵呵，夜间流量定向流量这种卖不出去的东西也好意思拿出来糊弄人？真当总理不知道么？ ","value": "Neutral","category":1},
{"name":"<400> 零碎年代里的支离破碎: [doge][doge]老板，这有WiFi吗？","value": "Neutral","category":2},
{"name":"<401> 低调的微尘: 报告总理，三大运营商在忽悠您。 ","value": "Negative","category":2},
{"name":"<402> 飞到月球Qu:  我的联通选择太多，不知道选哪个了[笑cry][笑cry][笑cry][笑cry][笑cry][笑cry] ","value": "Positive","category":1},
{"name":"<403> 二狗喵喵: 转发微薄[威武] ","value": "Positive","category":1},
{"name":"<404> 原罪之火: 转发微博 ","value": "Neutral","category":1},
{"name":"<405> Soledad7777: 不满意、谁大半夜不睡觉上网、而且在家里都有wifi好么@人民日报 @央视新闻 @中国联通 @中国移动 @中国电信    ","value": "Negative","category":1},
{"name":"<406> 奔跑吧奔跑吧跑跑: ","value": "Neutral","category":2},
{"name":"<407> 李大人人人: 忽悠百姓，忽悠总理！ ","value": "Negative","category":1},
{"name":"<408> Crysis_C: 忽悠，接着忽悠 ","value": "Negative","category":1},
{"name":"<409> 丶请叫我小夏童鞋: 对于你们这种欺诈行为，总理会制裁你们的","value": "Negative","category":3},
{"name":"<410> labcaff: ","value": "Neutral","category":2},
{"name":"<411> 孤独的FBI: ","value": "Neutral","category":2},
{"name":"<412> 极红寂幻: 呵呵嗒","value": "Neutral","category":3},
{"name":"<413> 网来时代: 你们满意么 ","value": "Neutral","category":1},
{"name":"<414> Jerrybazinga:  ","value": "Neutral","category":2},
{"name":"<415> 李虹誹: ","value": "Neutral","category":2},
{"name":"<416> Lose_yourself_: [笑cry]这尼玛降费是鼓励夜间多上网吗 ","value": "Neutral","category":1},
{"name":"<417> 手机用户3366413502: ","value": "Neutral","category":2},
{"name":"<418> ShanghaiTang金刚逸: ","value": "Neutral","category":2},
{"name":"<419> 花样作死二分队队长: 转发微薄[放假啦] ","value": "Neutral","category":1},
{"name":"<420> 凝语宝贝: 转发微薄[奥特曼] ","value": "Neutral","category":1},
{"name":"<421> dalabai:  ","value": "Neutral","category":2},
{"name":"<422> 捏---:  ","value": "Neutral","category":2},
{"name":"<423> 五味瓶: 回复@程飯:赞同","value": "Positive","category":1},
{"name":"<424> 香水百合的百合: ","value": "Neutral","category":2},
{"name":"<425> 章鱼-David: 移动最坑爹 ","value": "Negative","category":1},
{"name":"<426> 黄哲轩hzx: 三大粪箕有商有量 ","value": "Negative","category":2},
{"name":"<427> 山中大卫: ","value": "Neutral","category":4},



            ],
            links : [
            {"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<1> 星星的达人: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<2> 东昌王学增: 有用吗？ "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<3> 张文庆_Zwq: 呵呵"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<4> 小白_挚爱抽抽: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<5> Spectre_Dai: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<6> Eyebrow_who: 一点不满意，其实只有联通的降的比较靠谱，其他的什么夜间包节假日包……夜间和节假日我不会回家用wifi啊[微笑][拜拜]"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<7> 堇色沙滩: 前任总理管不住房价，没想到这任总理连流量都管不了。 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<8> WHY_Magneto: 总理！这就是在忽悠你呢。换汤不换药。 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<9> WOOWOWOO: @嗱_嗱嗱  "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<10> 风吹云走他乡客: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<11> 真假仙卖包子: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<12> Crazy_You: 总理至于你满不满意反正广大网友是不满意… "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<13> 吃辣条长大的孩纸: 不清零有个毛线用，哪个月不是日子没到就没流量了[顶] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<14> 马好颂: 好 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<15> 酒话斋主: 我好像听到了 pia  pia  pia "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<16> 瞧_布斯: 总理，这三个王八蛋不听话，忽悠您，打他[doge][doge][doge][doge] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<17> Mr金山老妖: 联通坑爹，说了等于没说，全国流量还是贵得要死 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<18> 犟牛Z向前冲: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<19> 轻酶煮酒ShawnTu_: mark "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<20> 小卒无命: 全是坑，属移动的最大！！！ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<21> 中国通信小小兵: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<22> 诺基亚WP粉丝团: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<23> 笑话好贱: 还是很贵[黑线] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<24> Taen_lx: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<25> ICEICEICE_YH: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<26> 深圳李文海: 就是忽悠人的[拳头] "},
{"source":"<6> Eyebrow_who: 一点不满意，其实只有联通的降的比较靠谱，其他的什么夜间包节假日包……夜间和节假日我不会回家用wifi啊[微笑][拜拜]","target":"<27> 柒夙QISU: 第一条就让我觉得用联通的真是棒棒的……"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<28> kimi啊啊啊: 为什么三个公司不可以共享号码 换运营公司意味着换手机号码真的很烦诶"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<29> Coke_Man: 新一轮眼花缭乱的营销活动而已，记得小时候看报纸每个月药品都会强制降价，可后来呢？"},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<30> 安东尼霍普金斯12: 电信 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<31> 月光如骨1218: 然而并没有便宜多少 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<32> 人渣哲: 感谢李克强总理，感谢三大运营商[泪][泪][泪][泪] "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<33> zhong乐悠悠2013: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<34> 军军仙深: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<35> Key-liu: 然而并没有什么卵用"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<36> 许敏俊xi: @落凝Yim "},
{"source":"<124> 专门调戏舰娘的萌豚提督: ","target":"<37> 请叫我绅士吧: 傻逼电信没有流量不清零？"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<38> Cherry小洋: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<39> 红河丶金刚芭比o: 联通就那点B东西 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<40> 西安靖春: 这个必须赞一个，总理都发话了[微笑] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<41> 深圳齐普生: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<42> Osi_C: 看完移动，“嗯~”；再往下看，“啊？！” "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<43> ASE一个葫芦:  "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<44> 观众席观众: 去NMB的夜间包定向包半年包，敢在正常流量包上减吗！？ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<45> BilsonLiu: 比较好奇这些措施什么时候开始，让利不大，然后再等两年就更扯淡了 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<46> 极品公子挚爱: 没什么实质性变化 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<47> 第七碗茶: 然而，我却觉得实用性不强。@菱洲藕榭_ @李闩闩  "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<48> 抽烟看球的老刘: 领导人发话就是不一样"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<49> 狼不才: 呵呵"},
{"source":"<89> Edwin今晚打老虎: 降个毛线，全特么在扯蛋！ ","target":"<50> Barnett-林: [吃惊]"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<51> 漫游冬天: 转发微博 "},
{"source":"<122> 沙包残念: 电信这个感觉还不错。。就是不知道四川电信会搞成啥样","target":"<52> 11-HamBurger: 联通这什么屌[打脸]草泥马之前定向流量最便宜的才九块钱啊！腾讯视频也才15块还不限流量！耍猴耍到这地步我建议和移动一起炸妈[打脸]"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<53> 编号0813: @MissJessie-MissMe 你的流量可以转赠给我了[害羞] "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<54> 雷大锤i: 还是联通良心"},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<55> 李凌纪: 看不出哪里降了，简直忽悠强哥"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<56> 中土世界旅行者: 没见着有什么真正优惠。夜间流量只有给值夜班的用用吧？电信宽带才提至4M，五年前就在用了 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<57> NISHIKI_SASAKI: 额~~~感觉对我没有什么影响的啊，要订的套餐还是一样啊~~~ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<58> 我是我_: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<59> 加纳凉子: 完全没看到降价 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<60> 山泉散漫绕街流: [赞] "},
{"source":"<231> 林松峰: 说的好[赞]","target":"<61> 大柚子猫: [草泥马]移动的闲时流量原来不是5元1G吗。。为毛还涨价了啊。。"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<62> 海宁邵峰: 又是套餐！ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<63> WP8全球新闻: 这TMD地叫降价... "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<64> 新浪科技: 你们满意么 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<65> 龚龑YAN-: 我喜欢联通流量可以转赠这点 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<66> 潘建文Amtor: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<67> 小黑猫ziye: "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<68> 龚玖伦Hunter: 联通的感觉还行，移动一如既往的坑"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<69> 杰王子_XJ: 糊弄人的"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<70> Kev_刘羽: Mark一下，准备退款 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<71> 馳胖儿: 糊弄鬼呢！！！这么213的政策。。。 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<72> luckyboy_20665: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<73> 肖丽君-lj: 转发微薄[爱你哦] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<74> OTT-汪: 优惠个妹！ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<75> 布绒琦乐屋: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<76> 丿晴天小猪丶: 大部分政策之前都有，甚至比这更优惠，只是大家都不知道罢了。 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<77> Emulex: [放大镜][放大镜][放大镜] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<78> 朱津宏Heath: 转发微博 "},
{"source":"<231> 林松峰: 说的好[赞]","target":"<79> Shaw_m: 总理说话不顶事儿，总经理说了才有用"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<80> 未完待续_tbc: 总经理骗总理。[挖鼻] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<81> Gonzalito瓜瓜: 大部分都是擦边球，没啥实质变化，移动那个最坑 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<82> 杨泽东015: @埃及艳后- 知道你4G的疾苦"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<83> 大连理财时间: 推荐[嘻嘻] "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<84> King_Liang2013: 没用 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<85> 君抹: 换汤不换药 不过宽带提速 到还是有一点 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<86> Disaur: 其实比美国部分运营商的流量费要便宜了吧 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<87> LRP不是牛奶瓶: 然而并没有什么卵用。 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<88> Lumia-Song-Mac: 都没诚意 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<89> Edwin今晚打老虎: 降个毛线，全特么在扯蛋！ "},
{"source":"<117> 许文广: 转发微博 ","target":"<90> heavens-yang: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<91> 悠悠谷: 完全木有看出有降价，移动的夜间流量套餐还涨了1倍！ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<92> SUN11308: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<93> faylin_blue: 能说简单点吗？我其实就是想知道我现在用的套餐是要降价呢，还是要增加流量，套餐内的流量也不清零吗？还是套餐都不变，就是动动我不怎么用的流量包意思一下？ "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<94> 江持的奇局rofL: 然而并没有什么卵用"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<95> 兰亭序xia:  "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<96> 地球是什么球: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<97> 星空漫语19910426: @李克强 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<98> 周锅圈: 联通电信良心。移动还是在打小算盘。[拜拜] "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<99> 欧欧琳琅: 还是联通实在啊 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<100> 曲占东: 没诚意，忽悠总理，该当何罪？[怒骂] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<101> 任怨RY: 然而，有个卵用？？？ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<102> 古波波的: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<103> 温雪微蜜2929106795: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<104> jessicagreat: 没有实质性变化 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<105> billinsh: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<106> 油油D: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<107> 大黄守着你:  @无敌小野猴 还能更不要脸一点么 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<108> 蒋科平: 总结的真好，看完发现有的不但没降还涨了。我啥也不要，你移动能在我现在这个套餐资费不变的基础上让我的5能用上4G就好。 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<109> 市井晓人: 躲躲闪闪 就是不好好说话  "},
{"source":"<321> 风中追风的林佳欣: 总理说：看来我的话不好使啊，是时候请王书记出马了[鄙视][鄙视] ","target":"<110> Kevin--Lau: [哈哈][哈哈][哈哈]赞同"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<111> CHen福森: 忽悠"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<112> xak简单: 转发微博 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<113> vermouth_APTX: 从10元70m到10元1g，可见你们之前的资费多坑爹了！ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<114> 北秋走马: 看完移动的就不想往下看了！！ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<115> 命运之匙: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<116> change变变: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<117> 许文广: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<118> fuyunc: 转发微博 "},
{"source":"<206> 挪威的森林0501: 三大运营商确实有推出了惠民政策，最明显的就是宽带的大幅提速。但也藏了不少小算盘甚至是“坑爹”的优惠：便宜的流量包时间设置在了半夜，好多措施都是换个名称的旧服务。当然还有各家此次借机大力推广4G业务。#运营商太机智# 白天的流量能优惠点不[疑问] ","target":"<119> 精卫埴海: 说得专业"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<120> 古月中心相心: 然而并没有什么卵用 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<121> 汐山芙伖Ukami: [微笑]"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<122> 沙包残念: 电信这个感觉还不错。。就是不知道四川电信会搞成啥样"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<123> reicn: 移动你妹喊你回家吃饭。 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<124> 专门调戏舰娘的萌豚提督: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<125> Abuser: 赤裸裸的打脸。 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<126> 奔波的鱼: 竟是虚的 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<127> honey当你: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<128> 豆腐羹V: 转发微博 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<129> liy-x: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<130> 低调的Liz: 不在乎说了多少话，而是在于谁说的[嘻嘻] "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<131> WIV哥哥: 不滿意 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<132> 前事莫言旧梦莫提: 呵呵 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<133> PapaverSomnus:  "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<134> Monster零号: 移动夜间1G还不能使用4G网。。。。。 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<135> pyb大大: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<136> GarethLE: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<137> 周鼎舵: [doge][喵喵]"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<138> CC二郎: 不咋的 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<139> 戴三个表Tadpole:  "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<140> 风沐浴张赛: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<141> 求不贰2: 降在哪 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<142> 乌衣弄小少: 我真特么日了[狗]了！这特么是降价？！！[doge][doge][doge] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<143> 风飘颺: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<144> 甄总萌萌哒: 这不光是质疑人民智商，还是质疑总理的智商，赞！ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<145> 没头脑姚: 转联通 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<146> 寒假不想看书君: 放NM的血啊，移动夜间流量10元1g，现在不是5元1g吗？rlgl！"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<147> 前峰w伟: 在网三年能买10块=1.5G 我居然够。。。@硬朗才俊 [喵喵] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<148> 我晕我又帅了vlv: 然而并没什么卵用…联通10元1.5G你得在网三年才能办[doge] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<149> 平-易: 毫无诚意 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<150> ACSun_zlz: 这也叫图，你是在逗我吗"},
{"source":"<54> 雷大锤i: 还是联通良心","target":"<151> sukiko789: 电信宽带，移动流量不清零"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<152> 坤少3599: 联通最没诚意，拿电信日的活动糊弄"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<153> 坛旺: 好热闹，而已。"},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<154> Alfred喜怒无常: 转需 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<155> sh-sf: 到底哪优惠。。。了"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<156> 锁向披靡: 跟我没任何关系，没一项复合优惠条件的。"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<157> 牵手奔跑89080: 也是个坑 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<158> Brandonwang13: 有个屁用 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<159> 金臣龙YoonA: 转发微博 "},
{"source":"<124> 专门调戏舰娘的萌豚提督: ","target":"<160> 利托里奥厨: 不满意，建议智障移动赶快申请倒闭"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<161> 花前肉下: 全是看上去很美系列， "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<162> Ocean_Qi: 大three可是一毛钱一兆 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<163> SHENPAI的微博: 降个屁，照样贵[doge] "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<164> 胖子的世界o_O: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<165> 雾中人Mr-D: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<166> 小曾伯伯: 不痛不痒，你们大爷的@中国电信 @中国移动 @中国联通 [怒][怒][怒] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<167> 奥利奥包子: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<168> 马鲛鱼_Huck: 我现在还是2G套餐"},
{"source":"<117> 许文广: 转发微博 ","target":"<169> 寻光阁主人: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<170> boy最佳听众: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<171> TonyNg: 不要脸。 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<172> X教授不在家: 毫无诚意 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<173> 黑色好心情: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<174> xvx墨鱼: 并没有什么卵用 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<175> 美国队长十三叔: 移动去死吧。"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<176> 疯猴砸王琳: 怎么感觉还是那么的贵啊   没有什么区别 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<177> 漫游环球: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<178> 史上最拽的大侠: 然而移动又来坑爹，夜间流量起个球用!! "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<179> AgentTSY: 好事啊！ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<180> 佛佑良善: @航海的萌琦: 还是贵的要死 "},
{"source":"<224> 阿邪: 这个力度还是继续忽悠总理吧 ","target":"<181> Mr聰小白: 上有政策下有对策的经典教科书式的典范，实在佩服 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<182> 左目大叔: 满意个毛！夜间优惠有个什么卵用！套餐资费哪有下降，明明变相推广套餐！宽带提速不就是把原来限制的带宽放开了而已，难道还要感谢他们吗？ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<183> 一枝不倒的枪: 无任何吸引力 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<184> LGD_Roden: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<185> Derrick-Rose-1: 换汤不换药 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<186> 即将爆炸: 降尼玛个鸡巴"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<187> 理查德查德: 这是侮辱总理的智商么 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<188> 周帛W: 看着好像是来捞钱的 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<189> 公子和小宝: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<190> a-sing-: 好像看不出什么很吸引人的，[睡][睡][睡] "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<191> 伟1006: 全TM是一堆鸡肋 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<192> Z-St13: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<193> Yoooo伪高冷: 移动对于我这个小市民来说 还是没什么特别的优势[拜拜]"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<194> 大猫和小猫1: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<195> MichaelDanZ: 我能说不怎么地嘛[抠鼻屎] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<196> 小蕾子哈哈-: 然而并没有什么卵用[拜拜] 移动不听话[打脸] 强哥削他[doge] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<197> 老K出品: 看中国移动又来忽悠总理和老百姓了。 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<198> magicKOU: 这都是些什么鬼！？开夜间流量顶个毛用！"},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<199> 15c爱木: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<200> Mast2r易昊: 口可口可 "},
{"source":"<117> 许文广: 转发微博 ","target":"<201> 吃葡萄说葡萄不吃不舒服司机:  "},
{"source":"<212> 尊贵黄铜: 并不满意","target":"<202> 不愿透露姓名的王心怿: 然而并没有什么卵用 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<203> 梦月天冰: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<204> 药师寺节园: 没感到下滑，对比移动太坑 "},
{"source":"<125> Abuser: 赤裸裸的打脸。 ","target":"<205> 温斯洛克: 这都是以前的方案，都用烂了"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<206> 挪威的森林0501: 三大运营商确实有推出了惠民政策，最明显的就是宽带的大幅提速。但也藏了不少小算盘甚至是“坑爹”的优惠：便宜的流量包时间设置在了半夜，好多措施都是换个名称的旧服务。当然还有各家此次借机大力推广4G业务。#运营商太机智# 白天的流量能优惠点不[疑问] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<207> 盐A桃: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<208> 祈祷者praying: 回复@初之心时尚:总经理不能忽悠，忽悠下总理还是可以的～至于流量不清零，三大运营商都不鸟老李～ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<209> 轻舞剑尘: 最讨厌人家一脸善意的问，请问您是吃大便还是吃屎呢？或者我们帮您准备了包翔套餐。妈的恶心到吐，我能不吃这些东西吗。"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<210> 石黑曜:  "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<211> 吃鹿的草: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<212> 尊贵黄铜: 并不满意"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<213> 钟先生的喜事: 确实不懂，以我短浅目光和捉急智商。 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<214> __王梓华: cx。"},
{"source":"<291> junwei: 转发微博 ","target":"<215> 李何冉: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<216> 后来不见不散: [doge] "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<217> 诺坎普666: 然而并没有什么卵用"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<218> 139王志涛: 工信部的官员们看看这@央视新闻 @王思聪 @工信微报 @新浪科技  "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<219> 身残志坚也无糖: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<220> 岳阳联通宽带受理XR: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<221> SimGenius: 联通能优先走本地流量吗→_→ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<222> Jerry的拉普拉斯变换: 丝毫没感觉到便宜[黑线][黑线]玩数字游戏，别骗我，我上过小学[失望][失望]#三大运营商提速降费# 没有政策的时候，@中国联通 搞活动1元1G流量，国家政策来了，美名其曰降费活动价10元1g[眼泪][眼泪]"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<223> yeleiyu: 然而并没什么卵用。。。。 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<224> 阿邪: 这个力度还是继续忽悠总理吧 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<225> AFannyGirl: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<226> 前任泡的茶: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<227> 禹stone: 不满意"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<228> 红颜还是蓝颜知己: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<229> 广西工业职业技术学院贴吧: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<230> 鬼束Komorebi: 转发微博 "},
{"source":"<79> Shaw_m: 总理说话不顶事儿，总经理说了才有用","target":"<231> 林松峰: 说的好[赞]"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<232> 余太的余先生: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<233> ChingYu_Sung: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<234> 偏执LeoH: 。。 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<235> 白--蓝: 提速后谁家能通过有公信力的网络测速，降费后谁家最便宜实惠，那就用谁家的。用户得到了哪家的优惠，自然会用脚投票，选择的就是满意的。 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<236> 丶MaiDang: 当全国人民是逗比 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<237> 前宸似锦: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<238> 晨明希: 糊弄傻逼呢，真不把总理当个事！夜间流量给谁用！来来来那几个老总你出来，我保证不打死你 "},
{"source":"<289> bzfdu: 基本上都没降，移动那个夜间1G现在就是5元，调整后居然变10元了[doge]电信那个4G套餐也很坑爹，价格跟移动现在的一样，但是移动送的是1G通用流量[拜拜]只有联通那个10块钱的包还行，不过也是要网龄限制的吧。 ","target":"<239> 改昵称什么的最头痛了: 也是艺术啊 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<240> 朕元大仙: 泥煤，泥煤！！刚花了100大洋买了1.5G "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<241> 飘渺-珂珂: 弱爆了，就是普通的电信日营销而已 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<242> 石头Life: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<243> 完颜许哲Jason-USTC: 其实没啥吸引力… "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<244> 我有一颗红蓝心: 都是文字游戏就不能同意一下，1G流量就是多少钱，和哪个时间段都没有关系"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<245> DJjiang_: 10元包1.5G省内流量@小镇土鳖青年 @Yowsen 1G全国流量包呢？ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<246> 黄曼塞: 领导们都白天睡觉，半夜上班咯？ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<247> 桔子酱Jamjamjam: 完全不满意 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<248> 玩坤: 上有政策，下有对策。坑是换汤不换药。 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<249> 红黑正正: 说了半天全是废话，等于没降 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<250> 贝贝贝_贝: 我就对流量不清零有兴趣[doge] 习大大真"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<251> 耳列偷: 转发微薄[放假啦] "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<252> 沈大霸: 联通良心啊 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<253> iPony-Ma: 总理，您怎么看…"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<254> MADshionn: 电信把用户体验搞搞上去就蛮好了、伐要每天10000打过来搞七捏三 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<255> 小科332: 呵呵 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<256> 可乐素巧克力控: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<257> 日斜影迟归: 我要回家，网速慢的甚少超过100KB还每个月25欧…"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<258> 烤火鸡腿: 我就笑笑，不说话 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<259> 柏吃支醉: 然而这并没有什么卵用"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<260> 明明就丶她比较温柔: 该赚的还是赚。 很多活动以前就有了。 听着好听实际上没有优惠多少 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<261> uncle____wang:  "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<262> 蛮满说要减肥好嘛: 夜间有什么用。。Wi-Fi在的好吗 联通好点 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<263> Cen儿里来的: 在侮辱总理和我们大众的智商吗？ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<264> Sunny上上签: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<265> Han志军: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<266> Vincent_SK_Fan: 轉發微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<267> YH铎: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<268> 宠物医生乐乐: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<269> 羊不少: 上面喊话，下面糊弄！都允许竞争不就没这破事了么，没劲！再说了一边要市场化运营，一边还要听政府话，矛盾，扭曲。"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<270> 大大Stefan: 说好的10块钱1G流量呢 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<271> 郭小雅爸爸的葡萄藤: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<272> 二毛我不饿: 有卵用？ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<273> neversaydie357: 中移动最王八 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<274> 传说世界真的可以: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<275> SMFWebo: 要不是李发话了这些铁公鸡的套餐指不定还要用几年 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<276> 徐笑笑Adam: 没劲 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<277> 秦-恒: [喵喵] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<278> 是个MADAO: 这算欺君之罪吧[怒] "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<279> 叮噹小麗: "},
{"source":"<89> Edwin今晚打老虎: 降个毛线，全特么在扯蛋！ ","target":"<280> 帷幕: 对就特么的忽悠"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<281> 少林收垃圾研究僧: 我10块钱3g的夜间流量。。。。 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<282> TEITA: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<283> 林松峰: 还是坑~换了一种挖坑的方式！ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<284> LLkey: 对总理的话 打下擦变球而已[挖鼻]套餐内的流量不还是那样吗"},
{"source":"<239> 改昵称什么的最头痛了: 也是艺术啊 ","target":"<285> 梁额头blingbling: @叉傅傅 [doge] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<286> 低调的山: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<287> 乐柚_: 并不满意 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<288> 静水长老: 夜间流量大优惠？！谁晚上回家没有WiFi？习大大都不赞成熬夜，运营商你想干嘛？[弱] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<289> bzfdu: 基本上都没降，移动那个夜间1G现在就是5元，调整后居然变10元了[doge]电信那个4G套餐也很坑爹，价格跟移动现在的一样，但是移动送的是1G通用流量[拜拜]只有联通那个10块钱的包还行，不过也是要网龄限制的吧。 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<290> 痞人北极熊16: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<291> junwei: 转发微博 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<292> 亦木lk: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<293> 秦邮俗人: 我是联通，10元1.5G省内流量包早就有了，现在还出来说，一点诚意都没有！这次的降价，我真替你们运营商心疼，利润好不容易从500%降到499%，真心不容易[笑cry] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<294> 青青蝶恋Pop: 转发微薄[织] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<295> 海宁邵峰: 又是套餐！ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<296> SH司翰: 转需 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<297> 随意昏沉: 没觉得降了多少"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<298> 太微子: 上有政策，下有对策。这群人永远不吃亏啊 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<299> 富牛同桌: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<300> 奔腾的大卫: 专线神马时候能大提速哇 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<301> 夢想家孟利峰:  "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<302> 郭小莱-Xiaolai: 听说都很忽悠人，坑爹声一大片。 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<303> 因为我叫甘大良: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<304> 笔下维城: 换汤不换药，坑谁呢 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<305> seele41: @天山云之家 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<306> 宫本笑外: 打擦边球，先说一下移动，其他真的没什么用就50元2G稍微便宜了一点，不也不知道这个更多城市不清零什么意思，联通嘛坑，1.5G包半年，我半年就用1.5G？包半年的废话不清零，不是包半年的呢，擦边球，电信也是坑谁天天玩夜间流量。三大运营商表面降价，其实没什么降价，国内的运营商应该到10元1G时代 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<307> 一木易青争: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<308> 红玫贝壳: 50元2G，有没有25元1G的？？ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<309> 张非仔: 有啥用，看着没优惠到哪去 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<310> YX-NUDTer:  "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<311> 东蹦蹦西跳跳: 就是忽悠人的，什么也没降！ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<312> 战争即和平xx即奴役无知即力量: 中国联通最操蛋 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<313> 陈诗文啊: 然而并没有什么卵用[微笑] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<314> 铁汉柔情喜感妹: 移动那个套餐老子特么都用了半年了你优惠在哪儿啊我次奥！ "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<315> 啊權權權兒: 然而并没有什么卵用 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<316> 黄立宏Hlh: +1 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<317> 康康YES:  "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<318> 三叔与露西: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<319> MorbidZoophilia_Cer: 并没什么卵用 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<320> P-H-B: 总理一句话为多少百姓争取了利益..周总理后中国又一位好总理 ！顶起！"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<321> 风中追风的林佳欣: 总理说：看来我的话不好使啊，是时候请王书记出马了[鄙视][鄙视] "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<322> Daniel_Dai_: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<323> 星马豪_: @星宇Iron  "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<324> 蕊落余馨: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<325> 王骏176: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<326> 五味瓶: 移动的最坑！ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<327> zw_stone: 并没有什么卵用 "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<328> 圣迷小子: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<329> 安妮5jhi18qol3: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<330> 加州风采: →_→ "},
{"source":"<117> 许文广: 转发微博 ","target":"<331> 风雨彩虹1970:  "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<332> 荐月: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<333> slim大祥: 三个这么合起伙来糊弄强哥 合适吗 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<334> 欧阳Page_one: 没看出有什么优惠的。。。 "},
{"source":"<209> 轻舞剑尘: 最讨厌人家一脸善意的问，请问您是吃大便还是吃屎呢？或者我们帮您准备了包翔套餐。妈的恶心到吐，我能不吃这些东西吗。","target":"<335> 你有种再说一遍: 假如总理再说一遍又一遍，他们可能又会推出一万块一万g流量！然而对于老百姓并没有什么卵用[紧张]"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<336> 行者秋莲: 总理说话也不很管用啊，还是利益好使 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<337> 龙岩学院电脑服务社: 还是太贵啊 "},
{"source":"<223> yeleiyu: 然而并没什么卵用。。。。 ","target":"<338> 计量的小竹子: 没没看出来。。降在哪里[doge]"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<339> Seika-5: 强哥你看看这三大粪箕是如何忽悠你的？ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<340> 石头小昊: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<341> 毛驴快快快跑: 总理的话果然掷地有声[good] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<342> 不死伪骑: 欺骗自己，欺骗人民，欺骗总理！！！@中国移动 @中国联通 @中国电信 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<343> 酱爆小咸鱼: 还是无比的坑，用户主要是用流量套餐的，而移动修改的资费是晚间闲时和假日的，晚间闲时有多少用户会开？ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<344> 梦月天冰: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<345> 不吃泡面WT: Repost "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<346> 追风筝的----孩子: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<347> sui豫er安: 又证明了一个真理 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<348> 刘淦新: 垄断，狂打强哥脸！ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<349> 杜蚊虫: 呵呵 你觉得呢"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<350> 翔蕉Man: [思考][思考][思考] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<351> 髮型影響網速: 中国联通啊，爱你不容易啊 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<352> 阿狸August: "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<353> 额尔得木图:  "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<354> 转角看见另一个自己: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<355> 海宝Diana: 要不是嫌换号麻烦，早换联通了，移动的闲时流量对我没用"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<356> slaywhospeak: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<357> 用户z5s: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<358> 落伍者9406: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<359> 千古传宋: 不满意，电信和移动没诚意。"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<360> 调哪星: 居然敢耍总理，简直係嫌命长[挖鼻][挖鼻]"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<361> 用户5524623994: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<362> 飞翔的石头1307: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<363> 战马孤影: [弱]不求放开市场，能携号转网也得让三大运营商当孙子 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<364> 广良W: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<365> 看風聼雨: @中国移动10086 移动毫无诚意，对我毫无影响！差评！ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<366> 云海飘星: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<367> 小屹爱吃肉: tmobile 40 美金全部无限 [喵喵] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<368> 柏飞先生: 诚意不足，总理比敢忽悠…… "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<369> 管跃辉023: 除了流量不清零、可交易、可转赠，其余就是把现有的各种优惠梳理了一下，换个外套而已，完全没有诚意！该岐山书记出马了！ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<370> 白百列: [委屈]"},
{"source":"<147> 前峰w伟: 在网三年能买10块=1.5G 我居然够。。。@硬朗才俊 [喵喵] ","target":"<371> cm968: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<372> 1zhu30: 哼哼哼"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<373> Mike主页: 忽悠总理 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<374> 沉梦未苏:  "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<375> 加油法拉利: 文盲脑残们你们换4G手机了吗？？手机都不支持4G有什么资格用4G？？ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<376> 刘-智-龙: 响应总理的号召～ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<377> 只是那个人-: 不"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<378> 玉淇淋: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<379> 80後縂裁: 糊弄傻子呢 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<380> 萝卜的萝_噢耶: 满意个屁！"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<381> 曲躍G风何: [睡]上有政策，下有对策，垄断的嘴脸"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<382> 再这么多僵尸广告粉我就怒弃微博: 有差么[闭眼]还是一样跪[闭眼]"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<383> Jorai: [右哼哼][左哼哼][怒骂] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<384> WindowsPhone玄隐: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<385> 我可怜我总是等待: 联通你这是套餐内不变，多用的降价。好机智呀！有多少人会另外开通流量包。fuck 还天天打电话问，烦不烦，不要钱啊！@中国联通 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<386> 自信未必成功: 转发微博 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<387> 绅士流亡: 好像对广大手机网民来说，没什么明显的实惠吧，总理您接着催吧，这三大傻不懂您懂的意思！！！！！[doge][弱]"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<388> yuanlinlynn: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<389> 零界点之沸: 你们这么忽悠总理，还真不怕总理向你们开刀咩？"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<390> 我书读得少你不要骗我哦: 没有实质性的惠民，三大运营商脑子被驴踢了么？ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<391> icu北极星: @财经杂志 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<392> J-concept童生: 中国电信 你的首选 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<393> I_Monster: 中国移动完全是糊弄人啊哈哈哈哈联通和电信才实在 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<394> 月西星沉: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<395> 追赶火车的男孩: 这仨小子不听话啊！是有多久没挨打了？ "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<396> 没吃药之前感觉自己萌萌哒: 坑"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<397> litenly: 尼玛，三坑连总理也敢坑！ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<398> 历途科技: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<399> 全武装幼女控: 呵呵，夜间流量定向流量这种卖不出去的东西也好意思拿出来糊弄人？真当总理不知道么？ "},
{"source":"<142> 乌衣弄小少: 我真特么日了[狗]了！这特么是降价？！！[doge][doge][doge] ","target":"<400> 零碎年代里的支离破碎: [doge][doge]老板，这有WiFi吗？"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<401> 低调的微尘: 报告总理，三大运营商在忽悠您。 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<402> 飞到月球Qu:  我的联通选择太多，不知道选哪个了[笑cry][笑cry][笑cry][笑cry][笑cry][笑cry] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<403> 二狗喵喵: 转发微薄[威武] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<404> 原罪之火: 转发微博 "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<405> Soledad7777: 不满意、谁大半夜不睡觉上网、而且在家里都有wifi好么@人民日报 @央视新闻 @中国联通 @中国移动 @中国电信    "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<406> 奔跑吧奔跑吧跑跑: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<407> 李大人人人: 忽悠百姓，忽悠总理！ "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<408> Crysis_C: 忽悠，接着忽悠 "},
{"source":"<389> 零界点之沸: 你们这么忽悠总理，还真不怕总理向你们开刀咩？","target":"<409> 丶请叫我小夏童鞋: 对于你们这种欺诈行为，总理会制裁你们的"},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<410> labcaff: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<411> 孤独的FBI: "},
{"source":"<259> 柏吃支醉: 然而这并没有什么卵用","target":"<412> 极红寂幻: 呵呵嗒"},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<413> 网来时代: 你们满意么 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<414> Jerrybazinga:  "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<415> 李虹誹: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<416> Lose_yourself_: [笑cry]这尼玛降费是鼓励夜间多上网吗 "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<417> 手机用户3366413502: "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<418> ShanghaiTang金刚逸: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<419> 花样作死二分队队长: 转发微薄[放假啦] "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<420> 凝语宝贝: 转发微薄[奥特曼] "},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<421> dalabai:  "},
{"source":"<22> 诺基亚WP粉丝团: 转发微博 ","target":"<422> 捏---:  "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<423> 五味瓶: 回复@程飯:赞同"},
{"source":"<64> 新浪科技: 你们满意么 ","target":"<424> 香水百合的百合: "},
{"source":"<0> 新浪科技: 一张图看清三大运营商提速降费方案，到底哪优惠。http://t.cn/RANMKIz  ","target":"<425> 章鱼-David: 移动最坑爹 "},
{"source":"<339> Seika-5: 强哥你看看这三大粪箕是如何忽悠你的？ ","target":"<426> 黄哲轩hzx: 三大粪箕有商有量 "},
{"source":"<409> 丶请叫我小夏童鞋: 对于你们这种欺诈行为，总理会制裁你们的","target":"<427> 山中大卫: "},


            ]
        }
    ]
};
var ecConfig = require('echarts/config');
function focus(param) {
    var data = param.data;
    var links = option.series[0].links;
    var nodes = option.series[0].nodes;
    if (
        data.source !== undefined
        && data.target !== undefined
    ) { //点击的是边
        var sourceNode = nodes.filter(function (n) {return n.name == data.source})[0];
        var targetNode = nodes.filter(function (n) {return n.name == data.target})[0];
        console.log("选中了边 " + sourceNode.name + ' -> ' + targetNode.name + ' (' + data.weight + ')');
    } else { // 点击的是点
        console.log("选中了" + data.name + '(' + data.value + ')');
    }
}
myChart.on(ecConfig.EVENT.CLICK, focus)

myChart.on(ecConfig.EVENT.FORCE_LAYOUT_END, function () {
    console.log(myChart.chart.force.getPosition());
});


                                       myChart.setOption(option);         
window.onresize = myChart.resize 
	})