require.config({
	paths:{
	 'echarts' : 'js/echarts/echarts-original',
	'echarts/chart/force' : 'js/echarts/echarts-original',
	'echarts/chart/chord' : 'js/echarts/echarts-original'
	 
	}
	});
	
	require(
	[
	'echarts',
	
	'echarts/chart/force',
	'echarts/chart/chord'
	
	],

	function(ec){
		var myChart = ec.init(document.getElementById('main4')); 
		option2 = {
     title : {
					text : "微博传播影响力图",
					subtext : "数据来自微博",
					x : "right",
					y : "bottom",
					padding : [ 10, 30 ],
					textStyle:{
					color:'#000000'
					}
				},
     tooltip : {
					trigger : "item",
					formatter : "{a0}:{b0}<br>情感值:{d}",
					borderRadius : 3,
					backgroundColor : "rgba(0,0,0,0.4)",
					padding : 4,
					axisPointer : {
						type : 'none',
						lineStyle : {
							color : '#4b8',
							width : 2,
							type : 'dashed'
						},
						crossStyle : {
							color : '#1e90ff',
							width : 5,
							type : 'dashed'
						},
						shadowStyle : {
							size : 'auto',
							color : 'rgba(150,150,150,0.3)'
						}
					}
				},animation:false,toolbox: {
        show : true,
        feature : {
           
            dataView : {show: true, readOnly: false},
          
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
  color : [ '#FF7F50','#CD5C5C',"#FFAAAA" , '#D2D2D2'],
    legend: {
        x: 'left',
        data:[{
						name : "一级重要节点",
						textStyle : {
							color : "#ff7f50"
						}
					},{
						name : "二级重要节点",
						textStyle : {
							color : "#CD5C5C"
						}
					},{
						name : "三级重要节点",
						textStyle : {
							color : "#FFAAAA"
						}
					},{
						name : "普通节点",
						textStyle : {
							color : "#D2D2D2"
						}
					}]
    },
    series : [
        {
            type:'force',
            name : "转发关系",
            ribbonType: false,
            categories : [
               {
						name : "一级重要节点",
						"symbolSize": 8
					},{
						name : "二级重要节点",
						"symbolSize": 6
					},
                 {

						name : "普通节点","symbolSize": 2

					},
                 {

						name : "三级重要节点","symbolSize": 4

					}
            ],
            itemStyle: {
                normal: {
                    label: {
                        show: false,
                        textStyle: {
                            color: '#333'
                        }
                    },
                    nodeStyle : {
                        brushType : 'both',
                        borderColor : 'rgba(255,215,0,0.4)',
                        borderWidth : 1
                    },
                    linkStyle: {
                        type: 'curve'

                    }
                },
                emphasis: {
                    label: {
                        show: false
                        // textStyle: null      // 默认使用全局文本样式，详见TEXTSTYLE
                    },
                    nodeStyle : {
                        //r: 30
                    },
                    linkStyle : {}
                }
            },
            useWorker: false,
            minRadius : 15,
            maxRadius : 25,
            gravity: 1.1,
            scaling: 1.1,
            roam: 'move',
            nodes:[{"name":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","value": "Neutral","category":0},
{"name":"<1> F张三丰F: 转发微博 ","value": "Neutral","category":2},
{"name":"<2> 3C将不在: 相信可以留一年 ","value": "Neutral","category":2},
{"name":"<3> 孩子一死我就来奶: 再来一次！[悲伤][悲伤] ","value": "Positive","category":2},
{"name":"<4> I-am-a-powerful-soul: 转发微博 ","value": "Neutral","category":2},
{"name":"<5> jian-zju: 那一年，都还有头发。。。 ","value": "Neutral","category":2},
{"name":"<6> yangdongki: AI之后最爱GDP，青涩的时光，哪怕没有总冠军也莫名的美好 ","value": "Positive","category":2},
{"name":"<7> 張筱童_V_V迷G4童: 转发微博 ","value": "Neutral","category":2},
{"name":"<8> LinZuQinag: 转发微博 ","value": "Neutral","category":2},
{"name":"<9> 艺J_Aznable: [泪][泪] ","value": "Neutral","category":2},
{"name":"<10> jesson陈杰: 转发微博 ","value": "Neutral","category":2},
{"name":"<11> 取啥都被用: 转发微博 ","value": "Neutral","category":2},
{"name":"<12> 凡小张就是这么有范儿:    永恒的经典，  马刺图腾。 ","value": "Positive","category":2},
{"name":"<13> 缘分的苍穹: gdp ","value": "Neutral","category":2},
{"name":"<14> 兔八他哥: 已经连续两个赛季说这估计是他们的最后一次，但是他们却走到了现在，不知道这一次会不会真的是最后 ","value": "Neutral","category":2},
{"name":"<15> 蒯Sainty: 转发微博 ","value": "Neutral","category":2},
{"name":"<16> Vanished_Glories_: 转发微博 ","value": "Neutral","category":2},
{"name":"<17> _Z-HILL_: 转发微博 ","value": "Neutral","category":2},
{"name":"<18> Super_JOJO_Lin: 转发微博 ","value": "Neutral","category":2},
{"name":"<19> 小xin未: 你觉得很帅吗？那我也转吧。","value": "Positive","category":2},
{"name":"<20> OYXOYXX: 转发微博 ","value": "Neutral","category":2},
{"name":"<21> 微醺-夏: 转发微博 ","value": "Neutral","category":2},
{"name":"<22> zzz____朱嘉宸: 石佛带走了一代人的青春 ","value": "Positive","category":2},
{"name":"<23> 墙角搓炉石: 转发微博 ","value": "Neutral","category":2},
{"name":"<24> 陈永聪_:   有些人即使离去了可精神还在啊[心] ","value": "Positive","category":2},
{"name":"<25> Billie-Joe_Armstrong: Repost ","value": "Neutral","category":2},
{"name":"<26> Aaron-Super7: 愿这一天来得迟一些[泪][泪] ","value": "Neutral","category":2},
{"name":"<27> 小木头也会疼: 回忆经典 ","value": "Positive","category":2},
{"name":"<28> 站在红场唱喀秋莎: 老而弥坚。 ","value": "Positive","category":2},
{"name":"<29> 剡溪山君: 马刺倒下的最大原因是帕克无法以最佳状态参战，老邓肯已经发挥到极致了，然而莱昂纳德被看死，也是帕克这个发动机工作不正常啊。。。 ","value": "Positive","category":2},
{"name":"<30> 方拓远: 看球不算多，只恨这几年才喜欢马刺，老军不死！ ","value": "Positive","category":2},
{"name":"<31> NovakDjokovic法网不夺冠不改名: [爱心][爱心][爱心][爱心][爱心][爱心][祈祷][祈祷][祈祷][祈祷][祈祷][祈祷][太阳][太阳][太阳][太阳][太阳] ","value": "Positive","category":2},
{"name":"<32> ridgwayliu: 转发微博 ","value": "Neutral","category":2},
{"name":"<33> D栋栋: 遥想当年，三驾马车所向无敌……岁月不饶人啊，科比都老了，艾弗森都退役好久了…… ","value": "Neutral","category":2},
{"name":"<34> 筑城小铃铛: 转发微博 ","value": "Neutral","category":2},
{"name":"<35> Season_in_the_sun_126: 转发微博 ","value": "Neutral","category":2},
{"name":"<36> 黄科大-孙海涛: 转发微博 ","value": "Neutral","category":2},
{"name":"<37> 张志成CHENG: 轉發微博 ","value": "Neutral","category":2},
{"name":"<38> sinjin: 转发微博 ","value": "Neutral","category":2},
{"name":"<39> ULISSES丶Yu: 转发微博 ","value": "Neutral","category":2},
{"name":"<40> 捍卫者RR: gdp","value": "Neutral","category":2},
{"name":"<41> 那天很愛笑: [强] ","value": "Positive","category":2},
{"name":"<42> 林大头Sir: 转发微博 ","value": "Neutral","category":2},
{"name":"<43> 横泾辣条哥: 转发微博 ","value": "Neutral","category":2},
{"name":"<44> Super_Kinopio: 转发微博 ","value": "Neutral","category":2},
{"name":"<45> verycute的蓝孩子丶: [失望]快意人生不言老，可是邓呆呆和地中海也该退役了 ","value": "Negative","category":2},
{"name":"<46> 人称胖子v: 转发微博 ","value": "Neutral","category":2},
{"name":"<47> RedDevils2002: ","value": "Neutral","category":2},
{"name":"<48> 蓦然如何到漠然: 难说再见 ","value": "Neutral","category":2},
{"name":"<49> 梦_随风飞扬: 秃子的毛啊 ","value": "Negative","category":2},
{"name":"<50> 原来的你在路上: 再来一年呗！ ","value": "Neutral","category":2},
{"name":"<51> 厚道微博: 转发微博 ","value": "Neutral","category":2},
{"name":"<52> 华水土木2014060班: 三架马车，不要走[悲伤]","value": "Negative","category":2},
{"name":"<53> 黄色的海绵宝宝裤子: 呆子秃子傻子[愛你] ","value": "Neutral","category":2},
{"name":"<54> 春天里的余小花: 最爱马刺！ ","value": "Positive","category":2},
{"name":"<55> 振宇_Eric: 快意人生不言老 ","value": "Positive","category":2},
{"name":"<56> zhanghw21: 转发微博 ","value": "Neutral","category":2},
{"name":"<57> 老嫩的水水: 转发微博 ","value": "Neutral","category":2},
{"name":"<58> 你一贱我就笑_Mango: [赞][赞] ","value": "Positive","category":2},
{"name":"<59> LadyJuventuslandia: 转发微博 ","value": "Neutral","category":2},
{"name":"<60> 季泽飞: 永远的GDP！ ","value": "Neutral","category":2},
{"name":"<61> 拼搏中的张小十一: [悲伤][悲伤][悲伤] ","value": "Negative","category":2},
{"name":"<62> 记事本的秘密: 还希望看到三位 ","value": "Neutral","category":2},
{"name":"<63> 褴褛牛: 转发微博 ","value": "Neutral","category":2},
{"name":"<64> _陪伴是最长的表白: 转发微博 ","value": "Neutral","category":2},
{"name":"<65> Syoyoukun: 帕克的表情好像唐马儒 ","value": "Neutral","category":2},
{"name":"<66> 杜某某某妍: [good][good][good]你们是最棒的 ","value": "Positive","category":2},
{"name":"<67> 富牛同桌: 转发微博 ","value": "Neutral","category":2},
{"name":"<68> 黝黑的我科: 转发微博 ","value": "Neutral","category":2},
{"name":"<69> 张琳Win: 转发微博 ","value": "Neutral","category":2},
{"name":"<70> 兜毡剩佛: 话别说他早，因为这样的话你们这些然早就说了好多年了[哈哈][哈哈][哈哈] ","value": "Negative","category":2},
{"name":"<71> huoer2010: 转发微博 ","value": "Neutral","category":2},
{"name":"<72> 20秃子不秃: 转发微博 ","value": "Neutral","category":2},
{"name":"<73> 酥泼鳗: 转发微博 ","value": "Neutral","category":2},
{"name":"<74> 幽月沁音: ","value": "Neutral","category":2},
{"name":"<75> SBB标: 转发微博 ","value": "Neutral","category":2},
{"name":"<76> nearly0925: 石佛退役吧！ ","value": "Neutral","category":2},
{"name":"<77> Cruise_宇: 应该还可以打多两年[阴险] ","value": "Positive","category":2},
{"name":"<78> -湯繼文-: [good] ","value": "Positive","category":2},
{"name":"<79> 徐杭er: 转发微博 ","value": "Neutral","category":2},
{"name":"<80> 妖怪哪里去2015: 转发微博 ","value": "Neutral","category":2},
{"name":"<81> -街头吃货-: 转发微博 ","value": "Neutral","category":2},
{"name":"<82> lovepeace我在英国天气晴: 转发微博 ","value": "Neutral","category":2},
{"name":"<83> 正宗潜龙: 转发微博 ","value": "Neutral","category":2},
{"name":"<84> 张莹Jessie: 转发微博 ","value": "Neutral","category":2},
{"name":"<85> 偷看了整个过程的韩文海绅士称: [笑cry]当年吉诺比利还没秃。。","value": "Positive","category":2},
{"name":"<86> 郑勇飞V: GDP[赞] ","value": "Positive","category":2},
{"name":"<87> 慈溪摊主: 转发微博 ","value": "Neutral","category":2},
{"name":"<88> 科布伦茨cheng: 真的是老了吗？ ","value": "Negative","category":2},
{"name":"<89> 天木三水: 转发微博 ","value": "Neutral","category":2},
{"name":"<90> 小白兔he小灰兔: 转发微博 ","value": "Neutral","category":2},
{"name":"<91> 香农罂粟: 转发微博 ","value": "Neutral","category":2},
{"name":"<92> love君于我如王: 转发微博 ","value": "Neutral","category":2},
{"name":"<93> 爱吃绿茶口香糖: 转发微博 ","value": "Neutral","category":2},
{"name":"<94> 劉篠洋: 大爱GDP ","value": "Positive","category":3},
{"name":"<95> 永清刘铮: @唐宇donyu  ","value": "Neutral","category":2},
{"name":"<96> khalil小北北: 你别bb","value": "Negative","category":2},
{"name":"<97> 我只在乎你2943311367: 转发微博 ","value": "Neutral","category":2},
{"name":"<98> 错觉zk24108: 转发微博 ","value": "Neutral","category":2},
{"name":"<99> R-R康: 转发微博 ","value": "Neutral","category":2},
{"name":"<100> 不吃豬肉的懶子跳跳: 快意人生不言老 ","value": "Positive","category":2},
{"name":"<101> Bryant_篮球心: 人老心未老 ","value": "Positive","category":2},
{"name":"<102> 唯1心繸: 转发微博 ","value": "Neutral","category":2},
{"name":"<103> 撸脑湿: 转发微博 ","value": "Neutral","category":2},
{"name":"<104> 电仔微博不见了TT: 不论能不能继续，只希望你们远离伤病的折磨 ","value": "Negative","category":2},
{"name":"<105> 吃藕丑ovo: 太美好的画面 ","value": "Positive","category":2},
{"name":"<106> 樱米小妖zmx: 转发微博 ","value": "Neutral","category":2},
{"name":"<107> _GinoChan: 转发微博 ","value": "Neutral","category":2},
{"name":"<108> 大马驹Chelsea: [悲伤] ","value": "Negative","category":2},
{"name":"<109> JN叶开: 快意人生，不说再见，不论久短 ","value": "Positive","category":2},
{"name":"<110> VialedeiCipress: 马刺GDP不知不觉走过这么多年 ","value": "Neutral","category":2},
{"name":"<111> my-heart-without-beating: Repost ","value": "Neutral","category":2},
{"name":"<112> Cola_Liu: [悲伤][悲伤][悲伤] ","value": "Negative","category":2},
{"name":"<113> Mrs_GZ: 转发微博 ","value": "Neutral","category":2},
{"name":"<114> 疑举袂1996: [泪流满面] ","value": "Negative","category":2},
{"name":"<115> 溫文爾雅的江南魯蛇: 哎 ","value": "Neutral","category":2},
{"name":"<116> Bryant裘: 转发微博 ","value": "Neutral","category":2},
{"name":"<117> 我是高冷_不是逗比: 转发微博 ","value": "Neutral","category":2},
{"name":"<118> -林二蛋: [鲜花] ","value": "Positive","category":2},
{"name":"<119> 科勒de指甲刀: GDP！！！ ","value": "Neutral","category":2},
{"name":"<120> Cecilia_Keyi: [爱心][爱心][爱心] ","value": "Neutral","category":2},
{"name":"<121> 赵菊花思密达: 不要走 ","value": "Neutral","category":2},
{"name":"<122> BlankPage解庆寒: 我大马刺老了 ","value": "Negative","category":2},
{"name":"<123> _God-is-NeymarJR_: 我的马刺[伤心] ","value": "Negative","category":2},
{"name":"<124> 虞璠: 转发微博 ","value": "Neutral","category":2},
{"name":"<125> Kent孤寂: 马刺老了 ","value": "Negative","category":2},
{"name":"<126> 宁放光芒nnn: 转发微博 ","value": "Neutral","category":2},
{"name":"<127> 手机用户3115992371: 转发微博 ","value": "Neutral","category":2},
{"name":"<128> -Queen-Q-: 我所执念的,还是08年我刚开始看球时活跃的那些人啊,无论NBA还是CBA,果然是老了,不能接受新鲜事物了[拜拜]岁月请善待GDP[祈祷] ","value": "Positive","category":2},
{"name":"<129> 忍辱负重丶: [心] ","value": "Positive","category":2},
{"name":"<130> CQxxLL: 在一年只要一年就好[泪流满面][泪流满面] ","value": "Negative","category":2},
{"name":"<131> 小智立志搞科研: 转发微博 ","value": "Neutral","category":2},
{"name":"<132> 有力度体育文化: 转发微博 ","value": "Neutral","category":2},
{"name":"<133> 嘟嘟肉-Wu: 有多么不愿说离别 ","value": "Negative","category":2},
{"name":"<134> 吴小志jerry: 快意人生不言老 ","value": "Positive","category":2},
{"name":"<135> Dong_Yl: 转发微博 ","value": "Neutral","category":2},
{"name":"<136> 爱迪生是小丑: 而我也十八岁了[doge][doge][doge] ","value": "Positive","category":2},
{"name":"<137> 91_Felix: 邓肯一退，波波也不远了[泪流满面][泪流满面][泪流满面] ","value": "Negative","category":2},
{"name":"<138> zeroHan: 转发微博 ","value": "Neutral","category":2},
{"name":"<139> 晓铃铛0: 转发微博 ","value": "Neutral","category":2},
{"name":"<140> 徐沅希: 今夏 我也38了[笑cry][笑cry][笑cry] ","value": "Positive","category":2},
{"name":"<141> 丁-渊: 转发微博 ","value": "Neutral","category":2},
{"name":"<142> 换好了22: 转发微博 ","value": "Neutral","category":2},
{"name":"<143> 不会打球的篮球狂: 转发微博 ","value": "Neutral","category":2},
{"name":"<144> 片熊piecebear: 不觉得过去了这么多年，你还在。若是此时离去，在你转身的一刻我们也只好向残忍地向过往的岁月挥手，说一句后会无期。[泪][泪] ","value": "Positive","category":2},
{"name":"<145> 墨更: 转发微博 ","value": "Neutral","category":2},
{"name":"<146> Carmenwennnnn: GDP,forever[爱心] [爱心] [爱心] ","value": "Positive","category":2},
{"name":"<147> 玩篮球也看足球: [泪][泪][泪][泪][泪] ","value": "Negative","category":2},
{"name":"<148> 贝克街的天然卷: 用青春爱过的人不会老！ ","value": "Positive","category":2},
{"name":"<149> 易小冻: 转发微博 ","value": "Neutral","category":2},
{"name":"<150> 张亚文xx: 加油，马刺不倒！ ","value": "Positive","category":2},
{"name":"<151> 答案iii: 转发微博 ","value": "Neutral","category":2},
{"name":"<152> Little_Horse_Brother: 转发微博 ","value": "Neutral","category":2},
{"name":"<153> 宫建坤: 转发微博 ","value": "Neutral","category":2},
{"name":"<154> 老于和小张: 转发微博 ","value": "Neutral","category":2},
{"name":"<155> J祥云阁: 怀念呀！ ","value": "Neutral","category":2},
{"name":"<156> 想做正能量的罐子: 快意人生不言老！永远的GDP[爱你] ","value": "Positive","category":2},
{"name":"<157> 邱宇阳ST: NBA里最喜欢马刺[微笑] ","value": "Positive","category":2},
{"name":"<158> 聿小頡: 还记得年少时的梦吗？像朵永不凋零的花！[心] ","value": "Positive","category":2},
{"name":"<159> 弹弹谈走鱼尾纹: Repost ","value": "Neutral","category":2},
{"name":"<160> 謝瑞奇ComeAndGet1T: Repost ","value": "Neutral","category":2},
{"name":"<161> 你484洒没错你94洒: [闭眼] ","value": "Neutral","category":2},
{"name":"<162> 轹文默: [泪][心] ","value": "Neutral","category":2},
{"name":"<163> 86599KG: 转发微博 ","value": "Neutral","category":2},
{"name":"<164> 旋木361: 时间既然不能逗留，总有一个人要先走[ok] ","value": "Neutral","category":2},
{"name":"<165> 小粥o泥浆: 快意人生不言老 ","value": "Positive","category":2},
{"name":"<166> 怎个事121: 转发微博 ","value": "Neutral","category":2},
{"name":"<167> BreathandLife-: 看到这些图就想哭[悲伤] ","value": "Negative","category":2},
{"name":"<168> 桺焱飏: @哗啦哗啦要变身  ","value": "Neutral","category":2},
{"name":"<169> urglyHm: [草泥马][草泥马][草泥马] ","value": "Negative","category":2},
{"name":"<170> 吕佳树Paul: 转发微博 ","value": "Neutral","category":2},
{"name":"<171> 天蝎1982: 转发微博 ","value": "Neutral","category":2},
{"name":"<172> XD文杰: 转发微博 ","value": "Neutral","category":2},
{"name":"<173> 叼着雪茄的熊猫: 为GDP点赞 ","value": "Positive","category":3},
{"name":"<174> Xys___: 转发微博 ","value": "Neutral","category":2},
{"name":"<175> _宁言: 淘汰了还说个毛 ","value": "Negative","category":2},
{"name":"<176> 周三早放假: 转发微博 ","value": "Neutral","category":2},
{"name":"<177> EnDKG: nono再退役我就睇都唔睇nba啦 ","value": "Neutral","category":2},
{"name":"<178> 路人甲的甲吧: [强][强][强][强][强][强] ","value": "Positive","category":2},
{"name":"<179> Miss_Tiger_CS: 每年都要说一次退役的事，不过真的好难过[泪][泪] ","value": "Negative","category":2},
{"name":"<180> 颜值太高不是我的错: [泪] ","value": "Negative","category":2},
{"name":"<181> redbeenie: [鼓掌][赞] ","value": "Positive","category":2},
{"name":"<182> 丶你好逗啊: 转发微博 ","value": "Neutral","category":2},
{"name":"<183> 洋_仔: 马刺被淘汰后，我觉得这赛季的季后赛就没啥看头了 ","value": "Neutral","category":2},
{"name":"<184> 咕噜噜的麦克格雷迪: 转发微博 ","value": "Neutral","category":2},
{"name":"<185> LeoKu坏好: 终究要面对离别，希望这一天来得慢一些。","value": "Neutral","category":2},
{"name":"<186> 十年面壁: NBA欠吉诺比利一个FMvp。否则，三兄弟功德圆满。 ","value": "Negative","category":2},
{"name":"<187> 灵感之源: 退了吧 ","value": "Neutral","category":2},
{"name":"<188> YanTangBaBa: 转发微博 ","value": "Neutral","category":2},
{"name":"<189> 安东尼不着急: 转发微博 ","value": "Neutral","category":2},
{"name":"<190> Wolfslan: 该拿的都拿够了，快退了，给年轻人留点机会吧[拜拜][拜拜][拜拜] ","value": "Negative","category":2},
{"name":"<191> Jessica杨的男神会发光: 大清早戳我泪点[泪][泪] ","value": "Negative","category":2},
{"name":"<192> 呆呆男神是eason: 当时的波波看着还那么年轻，当时的帕克还是个小正太，当时的吉诺比利还是个拥有飘逸长发的追风少年，当时的邓肯就更不用说了，还是个新秀。 ","value": "Positive","category":2},
{"name":"<193> ZJ_Bonne: 转发微博 ","value": "Neutral","category":2},
{"name":"<194> 上闲鱼清闲置: 转发微博 ","value": "Neutral","category":2},
{"name":"<195> 刮胡子会死星人: 转发微博 ","value": "Neutral","category":2},
{"name":"<196> 爱吃花生的麦小尖儿: 转发微博 ","value": "Neutral","category":2},
{"name":"<197> James-Yang: 明年又是冠军 ","value": "Positive","category":2},
{"name":"<198> 梁阿江: 今年觉得很遗憾，再打一年可好[悲伤] ","value": "Negative","category":2},
{"name":"<199> 无语森_tmys: 这三人有太多故事了，这种篇幅只是小打小闹 ","value": "Neutral","category":2},
{"name":"<200> 杉浦C_katagiiii: 不管如何都感謝這麼多年的陪伴，現在想想看從十幾歲開始支持的人除了kimi以外大概只剩他們還在拼搏了。 ","value": "Positive","category":2},
{"name":"<201> 倪大人: 转发微博 ","value": "Neutral","category":2},
{"name":"<202> 只想一生跟你走Lyi: 转发微博 ","value": "Neutral","category":2},
{"name":"<203> 他迷俄城035: 相信他们还会回来的。[悲伤][悲伤] ","value": "Negative","category":2},
{"name":"<204> 兔子在拼图: [泪流满面][泪流满面][泪流满面][泪流满面][泪流满面][泪流满面] ","value": "Negative","category":2},
{"name":"<205> 王家成Charles: 永远的GDP[心] ","value": "Positive","category":2},
{"name":"<206> 贫下中农扫缸弟: 虽然我对马刺的态度是路，但是我不希望他们退役。没了马刺，拿什么去检验强队。没了马刺，有多少猩密会狂 ","value": "Positive","category":2},
{"name":"<207> 布兰科_: 转发微博 ","value": "Neutral","category":2},
{"name":"<208> 什么昵称都有_这个呢: 转发微博 ","value": "Neutral","category":2},
{"name":"<209> 陈楚LiCe: GDP邓肯明明还能在搏斗，谁告诉我这不是真的 ","value": "Positive","category":2},
{"name":"<210> 盖着棉被开空调: 北基不哭，站起来日狗@khalil小北北  ","value": "Positive","category":2},
{"name":"<211> 渐行渐远渐不觉: 转发微博 ","value": "Neutral","category":2},
{"name":"<212> Black77-: [心][心] ","value": "Positive","category":2},
{"name":"<213> 叫才哥哇: 愿离别这天来得迟一些。。 ","value": "Neutral","category":2},
{"name":"<214> BRYANTFKR: [赞] ","value": "Positive","category":2},
{"name":"<215> 我忍等那一天: 转发微博 ","value": "Neutral","category":2},
{"name":"<216> specialshoot: 转发微博 ","value": "Neutral","category":2},
{"name":"<217> 摄影师老魏: 转发微博 ","value": "Neutral","category":2},
{"name":"<218> Sumus_龙: 再有一年就好[泪流满面][泪流满面][泪流满面][泪流满面][泪流满面] ","value": "Negative","category":2},
{"name":"<219> 甯宇1: 转发微博 ","value": "Neutral","category":2},
{"name":"<220> 半壺陳醋: 我家寵年輕時候是不是個大帥比！Manu，再打一年好不好！[泪] ","value": "Positive","category":2},
{"name":"<221> 你不必爱我-方炯镔: 转发微博 ","value": "Neutral","category":2},
{"name":"<222> maturemodestTYB彬: [泪] ","value": "Negative","category":2},
{"name":"<223> 甜椒_亻: Parker ","value": "Neutral","category":2},
{"name":"<224> 他是小迷糊: [泪][泪][泪]05年中考，那时候就是他们在打球，他们退役了，我的青春也结束了 ","value": "Negative","category":2},
{"name":"<225> 朱颖婕有一只肥羊: 萌石佛[悲伤] ","value": "Negative","category":2},
{"name":"<226> 第一口雪碧的滋味: [悲伤] ","value": "Negative","category":2},
{"name":"<227> 渔夫帽夫渔: 转发微博 ","value": "Neutral","category":2},
{"name":"<228> 丶电台司令: 转发微博 ","value": "Neutral","category":2},
{"name":"<229> 西门无雪7022: 转发微博 ","value": "Neutral","category":2},
{"name":"<230> 棋得丶可以: 5年级开始睇NBA的时候，马刺那年打败活塞夺冠，从我小学，初中，高中，到现在大学，马刺始终是以强队视人，GDP组合也一直陪伴我走过这10年的NBA球迷时光。虽然我早早想过天下无不散之筵席，GDP总有一天会解散，但现在可能真的要离别的时候还是觉得惋惜 ","value": "Positive","category":2},
{"name":"<231> 高山望云端: 转发微博 ","value": "Neutral","category":2},
{"name":"<232> 憨厚的小黄人01: 转发微博 ","value": "Neutral","category":2},
{"name":"<233> U-turn1983: 转发微博 ","value": "Neutral","category":2},
{"name":"<234> May人生海海Day: 转发微博 ","value": "Neutral","category":2},
{"name":"<235> 嘟嘟哥唔嗨森: 说好的老兵不死呢","value": "Neutral","category":2},
{"name":"<236> JIMNOR华: 转发微博 ","value": "Neutral","category":2},
{"name":"<237> SerenaHF: 托里帕克[爱你][爱你][爱你] ","value": "Positive","category":2},
{"name":"<238> 兰兰若水: 转发微博 ","value": "Neutral","category":2},
{"name":"<239> 敝帚千金: 转发微博 ","value": "Neutral","category":2},
{"name":"<240> yhz彩虹与你心连心手牵手: 转发微博 ","value": "Neutral","category":2},
{"name":"<241> Doctor------肖:  ","value": "Neutral","category":2},
{"name":"<242> 皮皮筱柠: 转发微博 ","value": "Neutral","category":2},
{"name":"<243> 北交大良民: 转发微博 ","value": "Neutral","category":2},
{"name":"<244> 陈秋任-: 知道你为什么干什么都那么水么？因为我看你一辈子都是俯视，你一辈子只能仰视。不要总是我一副我欠你钱的样子。关你屁事！[挤眼][挤眼][挤眼][黑线][黑线][黑线] ","value": "Neutral","category":2},
{"name":"<245> 鬼亡-魑魅魍魉: 不敢面对 ","value": "Neutral","category":2},
{"name":"<246> 小宇偶吧: [大哭] ","value": "Negative","category":2},
{"name":"<247> 海皇波塞东: @Arnolfini  ","value": "Neutral","category":2},
{"name":"<248> 拖延症拖拖拖: 转发微博 ","value": "Neutral","category":2},
{"name":"<249> 不就是一顿饭满: 你们是最棒的 ","value": "Positive","category":2},
{"name":"<250> 郝赟晕: never say goodbye ","value": "Neutral","category":2},
{"name":"<251> 我叫做文国威吖Ps丶头强: 转发微博 ","value": "Neutral","category":2},
{"name":"<252> lixiang14419: 转发微博 ","value": "Neutral","category":2},
{"name":"<253> 那一年橙色: 转发微博 ","value": "Neutral","category":2},
{"name":"<254> gyfh0810: 转发微博 ","value": "Neutral","category":2},
{"name":"<255> Miss_el1216: [悲伤]老野过时的年代 ","value": "Negative","category":2},
{"name":"<256> kemilulu: [心][心][心][心][心] ","value": "Positive","category":2},
{"name":"<257> 丁梓益艾特Kobe: 转发微博 ","value": "Neutral","category":2},
{"name":"<258> 打鲍洵的小baoxun817: 转发微博 ","value": "Neutral","category":2},
{"name":"<259> 轩萱轩-: 转发微博 ","value": "Neutral","category":2},
{"name":"<260> 我是个伪摇: 转发微博 ","value": "Neutral","category":2},
{"name":"<261> 轩萱轩-: 会回的 ","value": "Neutral","category":2},
{"name":"<262> 陈伟松同学: 转发微博 ","value": "Neutral","category":2},
{"name":"<263> 我要做她的小太阳: GDP[威武] ","value": "Positive","category":2},
{"name":"<264> 阿濱是個喜歡喜劇收尾的孤獨患者: Repost ","value": "Neutral","category":2},
{"name":"<265> 龍少-K: 转发微博 ","value": "Neutral","category":2},
{"name":"<266> 卢种花没得救了: 转发微博 ","value": "Neutral","category":2},
{"name":"<267> LYwing61:  ","value": "Neutral","category":2},
{"name":"<268> king灬星辰: 马刺已诠释了一切。 ","value": "Neutral","category":2},
{"name":"<269> 夏小ppppp:  ","value": "Neutral","category":2},
{"name":"<270> NBLAKERSKobe: 转发微博 ","value": "Neutral","category":2},
{"name":"<271> 24高伟: 不离不弃GDP ","value": "Positive","category":2},
{"name":"<272> 梁浩佳是一个好名字: 岁月像把剃头刀。 ","value": "Neutral","category":2},
{"name":"<273> SAS-LZY: 转发微博 ","value": "Neutral","category":2},
{"name":"<274> hdlegend: 转发微博 ","value": "Neutral","category":2},
{"name":"<275> 你的梦你来圆可以不: 转发微博 ","value": "Neutral","category":2},
{"name":"<276> 龍long的春天: 转发微博 ","value": "Neutral","category":2},
{"name":"<277> LarryZ: 了不起的三人组 ","value": "Positive","category":2},
{"name":"<278> 周峻丞ho: [心] ","value": "Positive","category":2},
{"name":"<279> JasperChau: [微风] ","value": "Neutral","category":2},
{"name":"<280> 郝旭军的微博: 其实我们都是波波维奇的粉丝。 ","value": "Positive","category":2},
{"name":"<281> DukeMcGrady: 转发微博 ","value": "Neutral","category":2},
{"name":"<282> 我没有微博帐号: 转发微博 ","value": "Neutral","category":2},
{"name":"<283> heLBsily: 转发微博 ","value": "Neutral","category":2},
{"name":"<284> 8o后_网虫: 转发微博 ","value": "Neutral","category":2},
{"name":"<285> _Piggg: [good][good][good] ","value": "Positive","category":2},
{"name":"<286> Hanover黄: 未来还是你们的，永远的21号新秀 ","value": "Neutral","category":2},
{"name":"<287> 单调忧郁刺伤我的心: 转发微博 ","value": "Neutral","category":2},
{"name":"<288> 噜啦噜啦嘞小强: 还是想邓肯赢[爱你]，可惜老了","value": "Positive","category":2},
{"name":"<289> MSN欣_: 时光老矣，初心未改，花落未央… ","value": "Positive","category":2},
{"name":"<290> NEW漫步慢步: 转发微博 ","value": "Neutral","category":2},
{"name":"<291> --Miss--YAO--: [爱你][爱你] ","value": "Positive","category":2},

                

            ],
            links : [
             {"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<1> F张三丰F: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<2> 3C将不在: 相信可以留一年 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<3> 孩子一死我就来奶: 再来一次！[悲伤][悲伤] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<4> I-am-a-powerful-soul: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<5> jian-zju: 那一年，都还有头发。。。 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<6> yangdongki: AI之后最爱GDP，青涩的时光，哪怕没有总冠军也莫名的美好 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<7> 張筱童_V_V迷G4童: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<8> LinZuQinag: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<9> 艺J_Aznable: [泪][泪] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<10> jesson陈杰: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<11> 取啥都被用: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<12> 凡小张就是这么有范儿:    永恒的经典，  马刺图腾。 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<13> 缘分的苍穹: gdp "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<14> 兔八他哥: 已经连续两个赛季说这估计是他们的最后一次，但是他们却走到了现在，不知道这一次会不会真的是最后 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<15> 蒯Sainty: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<16> Vanished_Glories_: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<17> _Z-HILL_: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<18> Super_JOJO_Lin: 转发微博 "},
{"source":"<14> 兔八他哥: 已经连续两个赛季说这估计是他们的最后一次，但是他们却走到了现在，不知道这一次会不会真的是最后 ","target":"<19> 小xin未: 你觉得很帅吗？那我也转吧。"},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<20> OYXOYXX: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<21> 微醺-夏: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<22> zzz____朱嘉宸: 石佛带走了一代人的青春 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<23> 墙角搓炉石: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<24> 陈永聪_:   有些人即使离去了可精神还在啊[心] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<25> Billie-Joe_Armstrong: Repost "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<26> Aaron-Super7: 愿这一天来得迟一些[泪][泪] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<27> 小木头也会疼: 回忆经典 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<28> 站在红场唱喀秋莎: 老而弥坚。 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<29> 剡溪山君: 马刺倒下的最大原因是帕克无法以最佳状态参战，老邓肯已经发挥到极致了，然而莱昂纳德被看死，也是帕克这个发动机工作不正常啊。。。 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<30> 方拓远: 看球不算多，只恨这几年才喜欢马刺，老军不死！ "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<31> NovakDjokovic法网不夺冠不改名: [爱心][爱心][爱心][爱心][爱心][爱心][祈祷][祈祷][祈祷][祈祷][祈祷][祈祷][太阳][太阳][太阳][太阳][太阳] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<32> ridgwayliu: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<33> D栋栋: 遥想当年，三驾马车所向无敌……岁月不饶人啊，科比都老了，艾弗森都退役好久了…… "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<34> 筑城小铃铛: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<35> Season_in_the_sun_126: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<36> 黄科大-孙海涛: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<37> 张志成CHENG: 轉發微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<38> sinjin: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<39> ULISSES丶Yu: 转发微博 "},
{"source":"<87> 慈溪摊主: 转发微博 ","target":"<40> 捍卫者RR: gdp"},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<41> 那天很愛笑: [强] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<42> 林大头Sir: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<43> 横泾辣条哥: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<44> Super_Kinopio: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<45> verycute的蓝孩子丶: [失望]快意人生不言老，可是邓呆呆和地中海也该退役了 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<46> 人称胖子v: 转发微博 "},
{"source":"<108> 大马驹Chelsea: [悲伤] ","target":"<47> RedDevils2002: "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<48> 蓦然如何到漠然: 难说再见 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<49> 梦_随风飞扬: 秃子的毛啊 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<50> 原来的你在路上: 再来一年呗！ "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<51> 厚道微博: 转发微博 "},
{"source":"<94> 劉篠洋: 大爱GDP ","target":"<52> 华水土木2014060班: 三架马车，不要走[悲伤]"},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<53> 黄色的海绵宝宝裤子: 呆子秃子傻子[愛你] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<54> 春天里的余小花: 最爱马刺！ "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<55> 振宇_Eric: 快意人生不言老 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<56> zhanghw21: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<57> 老嫩的水水: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<58> 你一贱我就笑_Mango: [赞][赞] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<59> LadyJuventuslandia: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<60> 季泽飞: 永远的GDP！ "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<61> 拼搏中的张小十一: [悲伤][悲伤][悲伤] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<62> 记事本的秘密: 还希望看到三位 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<63> 褴褛牛: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<64> _陪伴是最长的表白: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<65> Syoyoukun: 帕克的表情好像唐马儒 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<66> 杜某某某妍: [good][good][good]你们是最棒的 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<67> 富牛同桌: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<68> 黝黑的我科: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<69> 张琳Win: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<70> 兜毡剩佛: 话别说他早，因为这样的话你们这些然早就说了好多年了[哈哈][哈哈][哈哈] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<71> huoer2010: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<72> 20秃子不秃: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<73> 酥泼鳗: 转发微博 "},
{"source":"<109> JN叶开: 快意人生，不说再见，不论久短 ","target":"<74> 幽月沁音: "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<75> SBB标: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<76> nearly0925: 石佛退役吧！ "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<77> Cruise_宇: 应该还可以打多两年[阴险] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<78> -湯繼文-: [good] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<79> 徐杭er: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<80> 妖怪哪里去2015: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<81> -街头吃货-: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<82> lovepeace我在英国天气晴: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<83> 正宗潜龙: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<84> 张莹Jessie: 转发微博 "},
{"source":"<173> 叼着雪茄的熊猫: 为GDP点赞 ","target":"<85> 偷看了整个过程的韩文海绅士称: [笑cry]当年吉诺比利还没秃。。"},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<86> 郑勇飞V: GDP[赞] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<87> 慈溪摊主: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<88> 科布伦茨cheng: 真的是老了吗？ "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<89> 天木三水: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<90> 小白兔he小灰兔: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<91> 香农罂粟: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<92> love君于我如王: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<93> 爱吃绿茶口香糖: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<94> 劉篠洋: 大爱GDP "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<95> 永清刘铮: @唐宇donyu  "},
{"source":"<210> 盖着棉被开空调: 北基不哭，站起来日狗@khalil小北北  ","target":"<96> khalil小北北: 你别bb"},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<97> 我只在乎你2943311367: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<98> 错觉zk24108: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<99> R-R康: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<100> 不吃豬肉的懶子跳跳: 快意人生不言老 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<101> Bryant_篮球心: 人老心未老 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<102> 唯1心繸: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<103> 撸脑湿: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<104> 电仔微博不见了TT: 不论能不能继续，只希望你们远离伤病的折磨 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<105> 吃藕丑ovo: 太美好的画面 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<106> 樱米小妖zmx: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<107> _GinoChan: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<108> 大马驹Chelsea: [悲伤] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<109> JN叶开: 快意人生，不说再见，不论久短 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<110> VialedeiCipress: 马刺GDP不知不觉走过这么多年 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<111> my-heart-without-beating: Repost "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<112> Cola_Liu: [悲伤][悲伤][悲伤] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<113> Mrs_GZ: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<114> 疑举袂1996: [泪流满面] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<115> 溫文爾雅的江南魯蛇: 哎 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<116> Bryant裘: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<117> 我是高冷_不是逗比: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<118> -林二蛋: [鲜花] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<119> 科勒de指甲刀: GDP！！！ "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<120> Cecilia_Keyi: [爱心][爱心][爱心] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<121> 赵菊花思密达: 不要走 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<122> BlankPage解庆寒: 我大马刺老了 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<123> _God-is-NeymarJR_: 我的马刺[伤心] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<124> 虞璠: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<125> Kent孤寂: 马刺老了 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<126> 宁放光芒nnn: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<127> 手机用户3115992371: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<128> -Queen-Q-: 我所执念的,还是08年我刚开始看球时活跃的那些人啊,无论NBA还是CBA,果然是老了,不能接受新鲜事物了[拜拜]岁月请善待GDP[祈祷] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<129> 忍辱负重丶: [心] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<130> CQxxLL: 在一年只要一年就好[泪流满面][泪流满面] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<131> 小智立志搞科研: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<132> 有力度体育文化: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<133> 嘟嘟肉-Wu: 有多么不愿说离别 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<134> 吴小志jerry: 快意人生不言老 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<135> Dong_Yl: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<136> 爱迪生是小丑: 而我也十八岁了[doge][doge][doge] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<137> 91_Felix: 邓肯一退，波波也不远了[泪流满面][泪流满面][泪流满面] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<138> zeroHan: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<139> 晓铃铛0: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<140> 徐沅希: 今夏 我也38了[笑cry][笑cry][笑cry] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<141> 丁-渊: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<142> 换好了22: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<143> 不会打球的篮球狂: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<144> 片熊piecebear: 不觉得过去了这么多年，你还在。若是此时离去，在你转身的一刻我们也只好向残忍地向过往的岁月挥手，说一句后会无期。[泪][泪] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<145> 墨更: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<146> Carmenwennnnn: GDP,forever[爱心] [爱心] [爱心] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<147> 玩篮球也看足球: [泪][泪][泪][泪][泪] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<148> 贝克街的天然卷: 用青春爱过的人不会老！ "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<149> 易小冻: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<150> 张亚文xx: 加油，马刺不倒！ "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<151> 答案iii: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<152> Little_Horse_Brother: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<153> 宫建坤: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<154> 老于和小张: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<155> J祥云阁: 怀念呀！ "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<156> 想做正能量的罐子: 快意人生不言老！永远的GDP[爱你] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<157> 邱宇阳ST: NBA里最喜欢马刺[微笑] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<158> 聿小頡: 还记得年少时的梦吗？像朵永不凋零的花！[心] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<159> 弹弹谈走鱼尾纹: Repost "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<160> 謝瑞奇ComeAndGet1T: Repost "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<161> 你484洒没错你94洒: [闭眼] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<162> 轹文默: [泪][心] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<163> 86599KG: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<164> 旋木361: 时间既然不能逗留，总有一个人要先走[ok] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<165> 小粥o泥浆: 快意人生不言老 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<166> 怎个事121: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<167> BreathandLife-: 看到这些图就想哭[悲伤] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<168> 桺焱飏: @哗啦哗啦要变身  "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<169> urglyHm: [草泥马][草泥马][草泥马] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<170> 吕佳树Paul: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<171> 天蝎1982: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<172> XD文杰: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<173> 叼着雪茄的熊猫: 为GDP点赞 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<174> Xys___: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<175> _宁言: 淘汰了还说个毛 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<176> 周三早放假: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<177> EnDKG: nono再退役我就睇都唔睇nba啦 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<178> 路人甲的甲吧: [强][强][强][强][强][强] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<179> Miss_Tiger_CS: 每年都要说一次退役的事，不过真的好难过[泪][泪] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<180> 颜值太高不是我的错: [泪] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<181> redbeenie: [鼓掌][赞] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<182> 丶你好逗啊: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<183> 洋_仔: 马刺被淘汰后，我觉得这赛季的季后赛就没啥看头了 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<184> 咕噜噜的麦克格雷迪: 转发微博 "},
{"source":"<110> VialedeiCipress: 马刺GDP不知不觉走过这么多年 ","target":"<185> LeoKu坏好: 终究要面对离别，希望这一天来得慢一些。"},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<186> 十年面壁: NBA欠吉诺比利一个FMvp。否则，三兄弟功德圆满。 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<187> 灵感之源: 退了吧 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<188> YanTangBaBa: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<189> 安东尼不着急: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<190> Wolfslan: 该拿的都拿够了，快退了，给年轻人留点机会吧[拜拜][拜拜][拜拜] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<191> Jessica杨的男神会发光: 大清早戳我泪点[泪][泪] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<192> 呆呆男神是eason: 当时的波波看着还那么年轻，当时的帕克还是个小正太，当时的吉诺比利还是个拥有飘逸长发的追风少年，当时的邓肯就更不用说了，还是个新秀。 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<193> ZJ_Bonne: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<194> 上闲鱼清闲置: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<195> 刮胡子会死星人: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<196> 爱吃花生的麦小尖儿: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<197> James-Yang: 明年又是冠军 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<198> 梁阿江: 今年觉得很遗憾，再打一年可好[悲伤] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<199> 无语森_tmys: 这三人有太多故事了，这种篇幅只是小打小闹 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<200> 杉浦C_katagiiii: 不管如何都感謝這麼多年的陪伴，現在想想看從十幾歲開始支持的人除了kimi以外大概只剩他們還在拼搏了。 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<201> 倪大人: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<202> 只想一生跟你走Lyi: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<203> 他迷俄城035: 相信他们还会回来的。[悲伤][悲伤] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<204> 兔子在拼图: [泪流满面][泪流满面][泪流满面][泪流满面][泪流满面][泪流满面] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<205> 王家成Charles: 永远的GDP[心] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<206> 贫下中农扫缸弟: 虽然我对马刺的态度是路，但是我不希望他们退役。没了马刺，拿什么去检验强队。没了马刺，有多少猩密会狂 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<207> 布兰科_: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<208> 什么昵称都有_这个呢: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<209> 陈楚LiCe: GDP邓肯明明还能在搏斗，谁告诉我这不是真的 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<210> 盖着棉被开空调: 北基不哭，站起来日狗@khalil小北北  "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<211> 渐行渐远渐不觉: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<212> Black77-: [心][心] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<213> 叫才哥哇: 愿离别这天来得迟一些。。 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<214> BRYANTFKR: [赞] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<215> 我忍等那一天: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<216> specialshoot: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<217> 摄影师老魏: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<218> Sumus_龙: 再有一年就好[泪流满面][泪流满面][泪流满面][泪流满面][泪流满面] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<219> 甯宇1: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<220> 半壺陳醋: 我家寵年輕時候是不是個大帥比！Manu，再打一年好不好！[泪] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<221> 你不必爱我-方炯镔: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<222> maturemodestTYB彬: [泪] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<223> 甜椒_亻: Parker "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<224> 他是小迷糊: [泪][泪][泪]05年中考，那时候就是他们在打球，他们退役了，我的青春也结束了 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<225> 朱颖婕有一只肥羊: 萌石佛[悲伤] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<226> 第一口雪碧的滋味: [悲伤] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<227> 渔夫帽夫渔: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<228> 丶电台司令: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<229> 西门无雪7022: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<230> 棋得丶可以: 5年级开始睇NBA的时候，马刺那年打败活塞夺冠，从我小学，初中，高中，到现在大学，马刺始终是以强队视人，GDP组合也一直陪伴我走过这10年的NBA球迷时光。虽然我早早想过天下无不散之筵席，GDP总有一天会解散，但现在可能真的要离别的时候还是觉得惋惜 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<231> 高山望云端: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<232> 憨厚的小黄人01: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<233> U-turn1983: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<234> May人生海海Day: 转发微博 "},
{"source":"<85> 偷看了整个过程的韩文海绅士称: [笑cry]当年吉诺比利还没秃。。","target":"<235> 嘟嘟哥唔嗨森: 说好的老兵不死呢"},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<236> JIMNOR华: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<237> SerenaHF: 托里帕克[爱你][爱你][爱你] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<238> 兰兰若水: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<239> 敝帚千金: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<240> yhz彩虹与你心连心手牵手: 转发微博 "},
{"source":"<226> 第一口雪碧的滋味: [悲伤] ","target":"<241> Doctor------肖:  "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<242> 皮皮筱柠: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<243> 北交大良民: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<244> 陈秋任-: 知道你为什么干什么都那么水么？因为我看你一辈子都是俯视，你一辈子只能仰视。不要总是我一副我欠你钱的样子。关你屁事！[挤眼][挤眼][挤眼][黑线][黑线][黑线] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<245> 鬼亡-魑魅魍魉: 不敢面对 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<246> 小宇偶吧: [大哭] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<247> 海皇波塞东: @Arnolfini  "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<248> 拖延症拖拖拖: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<249> 不就是一顿饭满: 你们是最棒的 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<250> 郝赟晕: never say goodbye "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<251> 我叫做文国威吖Ps丶头强: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<252> lixiang14419: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<253> 那一年橙色: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<254> gyfh0810: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<255> Miss_el1216: [悲伤]老野过时的年代 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<256> kemilulu: [心][心][心][心][心] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<257> 丁梓益艾特Kobe: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<258> 打鲍洵的小baoxun817: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<259> 轩萱轩-: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<260> 我是个伪摇: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<261> 轩萱轩-: 会回的 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<262> 陈伟松同学: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<263> 我要做她的小太阳: GDP[威武] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<264> 阿濱是個喜歡喜劇收尾的孤獨患者: Repost "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<265> 龍少-K: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<266> 卢种花没得救了: 转发微博 "},
{"source":"<52> 华水土木2014060班: 三架马车，不要走[悲伤]","target":"<267> LYwing61:  "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<268> king灬星辰: 马刺已诠释了一切。 "},
{"source":"<174> Xys___: 转发微博 ","target":"<269> 夏小ppppp:  "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<270> NBLAKERSKobe: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<271> 24高伟: 不离不弃GDP "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<272> 梁浩佳是一个好名字: 岁月像把剃头刀。 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<273> SAS-LZY: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<274> hdlegend: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<275> 你的梦你来圆可以不: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<276> 龍long的春天: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<277> LarryZ: 了不起的三人组 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<278> 周峻丞ho: [心] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<279> JasperChau: [微风] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<280> 郝旭军的微博: 其实我们都是波波维奇的粉丝。 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<281> DukeMcGrady: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<282> 我没有微博帐号: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<283> heLBsily: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<284> 8o后_网虫: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<285> _Piggg: [good][good][good] "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<286> Hanover黄: 未来还是你们的，永远的21号新秀 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<287> 单调忧郁刺伤我的心: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<288> 噜啦噜啦嘞小强: 还是想邓肯赢[爱你]，可惜老了"},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<289> MSN欣_: 时光老矣，初心未改，花落未央… "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<290> NEW漫步慢步: 转发微博 "},
{"source":"<0> 新浪体育: 卫冕冠军马刺，倒在季后赛首轮，邓肯、帕克与吉诺比利终究终难敌岁月的流逝。不知不觉间，“法国跑车”已经33岁，而39岁的邓肯，和即将38岁的吉诺比利，今夏合同到期，或许他们会选择退役，或许GDP就此画下终止。结束还是继续？但愿…...[心]不说离别！组图回顾GDP的快意人生：http://t.cn/R27Dzs","target":"<291> --Miss--YAO--: [爱你][爱你] "},

            ]
        }
    ]
};
var ecConfig = require('echarts/config');
function focus(param) {
    var data = param.data;
    var links = option.series[0].links;
    var nodes = option.series[0].nodes;
    if (
        data.source !== undefined
        && data.target !== undefined
    ) { //点击的是边
        var sourceNode = nodes.filter(function (n) {return n.name == data.source})[0];
        var targetNode = nodes.filter(function (n) {return n.name == data.target})[0];
        console.log("选中了边 " + sourceNode.name + ' -> ' + targetNode.name + ' (' + data.weight + ')');
    } else { // 点击的是点
        console.log("选中了" + data.name + '(' + data.value + ')');
    }
}
myChart.on(ecConfig.EVENT.CLICK, focus)

myChart.on(ecConfig.EVENT.FORCE_LAYOUT_END, function () {
    console.log(myChart.chart.force.getPosition());
});


                                       myChart.setOption(option2);         
 window.onresize = myChart.resize  
	})